import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
];
const decisionFile = '产品文档/prd-workflow/decisions/box-recognition-step.decision.md';

const pageName = '选择识别内容';
const route = '/homework → 识别作业资料 → 选择识别内容';
const moduleName = '识别作业资料';

function activateRecognizeQuestions(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到选择识别内容', step: 'frame_and_review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

function activateMoreTools(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到选择识别内容', step: 'frame_and_review' },
    { type: 'openPanel' as const, label: '展开更多工具菜单', panel: 'BoxStepMoreTools' },
    { type: 'scrollTo' as const, label: '定位更多工具入口', anchorId },
    { type: 'highlight' as const, label: '高亮更多工具入口', anchorId },
  ];
}

function activateFileRoleDialog() {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'openDialog' as const, label: '打开文件用途分配弹窗', dialog: 'SelectModeFileRoleDialog' },
    { type: 'scrollTo' as const, label: '定位文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
    { type: 'highlight' as const, label: '高亮文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
  ];
}

export const boxRecognitionStepRegistry: RequirementRegistry = {
  registryId: 'box-recognition-step',
  pageName,
  route,
  module: moduleName,
  description: '记录步骤 3「选择识别内容」的完整页面逻辑，覆盖资料选框呈现、右侧悬浮操作、右侧空状态、文件用途弹窗、自动切题、补充资料、更换资料、重新上传和增量识别等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'BOX_STEP-001',
      title: '框选统计信息',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'region',
      objectName: '已选中/已框选统计文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-selection-stats',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-selection-stats'),
      display: {
        title: '框选统计信息',
        description: '资料预览区右上角以深色悬浮信息条展示「已选中 X 题 / 已框选 Y 题」。',
        fields: ['已选中 X 题', '已框选 Y 题'],
        states: [
          '无框时：已选中和已框选均显示为 0',
          '框选变化时：统计数字随新增、删除或切换识别框选中状态同步刷新',
          '切题中（首次）：统计暂不显示',
          '切题中（追加）：统计正常显示',
        ],
      },
      operation: {
        title: '统计刷新规则',
        description: '统计文案不可点击、不可交互。选中数量变化后，「开始识别」按钮根据已选中数量判断是否可用。',
        permission: '无额外权限限制',
        dataFlow: '统计根据当前资料页的识别框和选中状态计算。',
        exceptions: '自动切题未检测到内容时，统计保持为 0，用户可手动画框后刷新。',
      },
      acceptance: [
        '已框选数字正确显示',
        '已选中数字正确显示',
        '统计角标应显示在统计文案旁边',
        '统计角标不应挂在清空按钮上',
        '无框时两个数字均显示为 0',
      ],
      source: { decisionFile, decisionObject: '框选统计信息', relatedFiles },
    },
    {
      id: 'BOX_STEP-014',
      title: '清空框选操作',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '清空框选悬浮球',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-clear-action',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-clear-action'),
      display: {
        title: '清空框选入口',
        description: '资料预览区右侧「开始识别」下方显示清空圆形图标按钮和文字按钮「清空」。有可操作框时为红色可点击状态；无可操作框或切题中时置灰；识别进行中时隐藏。',
        fields: ['清空圆形图标按钮', '清空文字按钮'],
        states: [
          '可用态：存在可操作框时红色可点击',
          '禁用态：无可操作框或切题中时置灰',
          '识别中：清空入口隐藏',
        ],
      },
      operation: {
        title: '清空框选',
        description: '1、点击「清空」弹出确认弹窗「确认清空所有切题框吗？」。\n2、确认后删除全部框选区域和选中状态。\n3、取消后已有框选和选中状态保持不变。\n4、清空后统计归零，「开始识别」变为不可点击。',
        permission: '无额外权限限制',
        dataFlow: '清空只处理框选区域和选中状态，不删除已上传资料。',
        exceptions: '无可操作框时按钮置灰，不弹确认弹窗。',
      },
      acceptance: [
        '清空需求角标应显示在清空悬浮球旁边',
        '有可操作识别框时清空按钮可点击',
        '无可操作识别框时清空按钮置灰',
        '点击清空应先弹出确认弹窗',
        '确认后已选中和已框选数量归零',
      ],
      source: { decisionFile, decisionObject: '清空框选操作', relatedFiles },
    },
    {
      id: 'BOX_STEP-002',
      title: '开始识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '开始识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-start-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-start-btn'),
      display: {
        title: '开始识别按钮',
        description: '资料预览区右侧中部，绿色圆形悬浮球和下方「开始识别」文字按钮。有选中框且不在处理中时绿色可点击，无选中框或处理中时置灰。步骤4核对时仍可继续使用。',
        fields: ['开始识别悬浮球', '开始识别文字按钮', '选中数量'],
        states: [
          '可用态：有选中框且不在处理中 → 绿色可点击',
          '禁用态：无选中框或处理中 → 灰色不可点击',
        ],
      },
      operation: {
        title: '开始识别',
        description: '1、点击后系统根据已选中的框裁剪图片区域，调用 AI 识别，进入步骤4。\n2、仅识别题目模式：所有框按题目处理，右侧只展示题干。\n3、题目+答案模式：题目框走完整识别，答案框走答案提取，右侧展示题干+答案/解析。\n4、第4步可继续新增框选后再次点击识别，结果按题号插入列表。\n5、第4步可重新框选已有题目后再次识别，同题号结果覆盖原题卡。',
        permission: '无额外权限限制',
        dataFlow: '将已选中框、裁剪图片、识别模式和学科信息发送给 AI 识别服务。',
        exceptions: '识别中可点击「取消识别」退出识别状态，回到步骤3并回显识别前的选框和选中状态。识别失败时保留原框和选中状态，右侧显示错误信息。',
      },
      acceptance: [
        '有选中框时按钮可用',
        '无选中框时按钮置灰',
        '切题中按钮置灰',
        '识别方式标签正确显示',
        '点击后进入识别流程',
        '第4步新增框选后可继续点击开始识别',
        '第4步重复框选同题号题干后应覆盖原题卡',
      ],
      source: { decisionFile, decisionObject: '开始识别按钮', relatedFiles },
    },
    {
      id: 'BOX_STEP-003',
      title: '右侧空状态引导',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '右侧空状态引导文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-empty-state',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-empty-state'),
      display: {
        title: '右侧空状态',
        description: '点击开始识别前，右侧面板显示空状态引导文案。仅识别题目模式：「框选题目并选中后，点击「开始识别」，小乐会自动为您识别题目，完成识别后，您可在右侧以图片或文字的形式分模块查看每道题目」。题目+答案模式：「框选题目并选中后，点击「开始识别」，小乐会为您自动识别题目，并进行题目和答案的自动匹配。完成识别后，您可在右侧以图片或文字的形式分模块查看每道题的题干与答案/解析」。有选中框时下方显示「已选中 X 个识别框」。',
        fields: ['空状态引导文案', '已选中 X 个识别框'],
        states: ['空态（无题目卡片）', '有选中框时显示已选中数量'],
      },
      operation: {
        title: '纯展示',
        description: '引导文案和已选中数量不可点击、不可交互。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['两种模式文案不同', '已选中数量正确', '与操作按钮状态一致'],
      source: { decisionFile, decisionObject: '右侧面板空态说明', relatedFiles },
    },
    {
      id: 'BOX_STEP-004',
      title: '文件用途分配弹窗（识别题目和答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'dialog',
      objectName: '文件用途分配弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-role-dialog',
      anchorStatus: 'implemented',
      activate: activateFileRoleDialog(),
      display: {
        title: '文件用途分配弹窗',
        description: '「题目+答案（不同文件）」模式下补充资料后弹出「指定文件用途」弹窗。仅显示本次新增文件，说明文案为「检测到您新增了 X 个文件，请分别为新增文件指定用途」。每份文件可独立选择「题目文件」或「答案文件」。底部展示「取消」和「确认，开始处理」按钮，所有文件分配后确认按钮可用。',
        fields: ['指定文件用途', '文件名', '题目文件按钮', '答案文件按钮', '取消', '确认，开始处理'],
        states: [
          '文件用途选中态：绿色高亮',
          '确认按钮：所有文件分配后可用',
          '确认按钮禁用态：存在未分配用途的文件时不可点击',
        ],
      },
      operation: {
        title: '文件用途分配',
        description: '1、每份文件独立选择用途，互不影响。\n2、点击已选中按钮可取消选择。\n3、所有文件分配后点击「确认，开始处理」，新增文件按用途进入当前流程。\n4、取消或关闭弹窗时，撤回本次补充文件，提示「已取消本次补充资料」，原有框选和识别结果不变。',
        permission: '无额外权限限制',
        dataFlow: '分配结果传给后续流程，决定新增文件的标签、显示顺序、自动切题范围和答案匹配范围。',
        exceptions: '取消或关闭弹窗时撤回本次补充文件，原有框选和识别结果不变。',
      },
      acceptance: [
        '文件独立选择文件用途',
        '点击已选可取消',
        '补充资料后仅显示本次新增文件',
        '文案按场景正确切换',
        '取消或关闭弹窗后应撤回本次新补充文件',
        '取消或关闭弹窗后应提示「已取消本次补充资料」',
        '取消或关闭弹窗后原有框选和识别结果应保持不变',
      ],
      source: { decisionFile, decisionObject: '文件用途分配弹窗 / 交互：补充资料后文件用途弹窗取消/关闭的处理', relatedFiles },
    },
    {
      id: 'BOX_STEP-005',
      title: '补充资料入口',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '补充资料按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-supplement-upload',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-supplement-upload'),
      display: {
        title: '补充资料按钮',
        description: '资料预览区右下角「更多工具」展开后显示「补充资料」按钮。该入口只用于补充本地资料，资料选择弹窗中隐藏资源库 Tab。',
        fields: ['更多工具', '补充资料'],
        states: [
          '更多工具未展开：仅显示悬浮入口',
          '更多工具已展开：显示补充资料按钮',
          '资料选择弹窗：隐藏资源库 Tab',
        ],
      },
      operation: {
        title: '补充资料',
        description: '1、点击「补充资料」打开资料选择弹窗，只保留本地上传入口。\n2、仅识别题目和题目+答案（同文件）模式：上传后直接对新增资料自动切题，不弹文件用途弹窗。\n3、题目+答案（不同文件）模式：上传后弹出文件用途分配弹窗，取消则撤回补充文件。\n4、补充后保留已有框选和选中状态，仅对新页面自动切题。',
        permission: '无额外权限限制',
        dataFlow: '新文件追加到现有列表末尾，已有框选和识别结果不被清空。用途分配若被取消，新增文件从当前任务撤回。',
        exceptions: '取消或关闭文件用途分配弹窗时，提示「已取消本次补充资料」。',
      },
      acceptance: [
        '更多工具展开后显示补充资料入口',
        '补充资料入口打开资料选择弹窗时隐藏资源库 Tab',
        '仅识别题目模式不弹文件用途分配弹窗',
        '题目+答案（同文件）模式不弹文件用途分配弹窗',
        '题目+答案（不同文件）模式按文件用途规则弹窗',
        '取消文件用途分配后应撤回本次补充文件',
        '已有框选保留',
      ],
      source: { decisionFile, decisionObject: '按钮：更多工具里的「补充资料」资料来源范围 / 交互：补充资料后文件用途弹窗取消/关闭的处理', relatedFiles },
    },
    {
      id: 'BOX_STEP-012',
      title: '更换资料入口与清空确认',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '更换资料按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-modify-files',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-modify-files'),
      display: {
        title: '更换资料入口与确认弹窗',
        description: '「更多工具」展开后显示「更换资料」按钮。已有识别结果时点击弹出确认弹窗：「确认更换资料吗？更换资料，将清空当前已识别的内容，并且需要重新选择识别方式。」',
        fields: ['更多工具', '更换资料', '确认更换资料吗？', '取消', '确认'],
        states: ['更多工具未展开', '更多工具已展开', '无识别结果', '已有识别结果', '确认弹窗打开状态'],
      },
      operation: {
        title: '返回上传资料步骤',
        description: '1、点击「更换资料」后更多工具面板收起，返回步骤1。\n2、已有识别结果时先弹窗确认，确认后清空题目和框选结果。\n3、无识别结果时直接返回步骤1。\n4、返回后回显已上传资料和对应识别范围。\n5、确认返回后，后续删除、调整范围或继续上传均按最新资料列表重新处理。',
        permission: '无额外权限限制',
        dataFlow: '确认后清空题目、答案、框选、文件用途和识别方式，保留资料和识别范围供继续管理。',
        exceptions: '取消确认时保持当前步骤和识别结果不变。打开确认弹窗时「更多工具」面板应收起。',
      },
      acceptance: [
        '更多工具展开后显示更换资料入口',
        '点击更换资料后更多工具面板应收起',
        '已有识别结果时点击更换资料应先展示清空提示',
        '确认后应返回上传资料步骤并清理当前识别进度',
        '返回上传资料步骤后应回显已上传资料和对应识别范围',
        '无识别结果时可直接返回上传资料步骤',
        '取消后应保持当前步骤和已有识别结果',
      ],
      source: {
        decisionFile: '产品文档/prd-workflow/decisions/upload-files-step.decision.md',
        decisionObject: '交互：返回「上传资料」的入口 / 逻辑：更换资料后的重算范围 / 状态：资料重新处理期间的页面操作 / 交互：更多工具展开状态在流程切换后的恢复规则',
        relatedFiles,
      },
    },
    {
      id: 'BOX_STEP-006',
      title: '重新上传按钮与确认弹窗',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '重新上传按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-reupload-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-reupload-btn'),
      display: {
        title: '重新上传按钮',
        description: '「继续上传」按钮左侧，灰色文字样式。点击弹出确认弹窗：「确认更换资料吗？更换资料，将清空当前已有的识别结果。」',
        fields: ['重新上传', '确认弹窗'],
        states: ['可点击', '核对识别结果步骤隐藏'],
      },
      operation: {
        title: '重新上传',
        description: '1、点击弹出确认弹窗。\n2、确认后清空框选、识别模式、文件用途和识别结果，回到步骤1并回显已上传文件和识别范围。',
        permission: '无额外权限限制',
        dataFlow: '确认后清空框选、识别模式、文件用途和识别结果，回到步骤1并回显文件列表。',
        exceptions: '确认弹窗可取消，取消后保持当前状态不变。',
      },
      acceptance: [
        '点击弹出确认弹窗',
        '确认后回到步骤1并回显已上传文件和识别范围',
        '取消保持当前状态',
        '核对识别结果步骤不显示',
      ],
      source: { decisionFile, decisionObject: '重新上传', relatedFiles },
    },
    {
      id: 'BOX_STEP-007',
      title: '取消识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '取消识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-pause-cancel-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-pause-cancel-btn'),
      display: {
        title: '取消识别按钮',
        description: '识别过程中，右侧面板显示进度提示和「取消识别」按钮（灰色）。',
        fields: ['取消识别'],
        states: ['识别中：显示'],
      },
      operation: {
        title: '取消识别',
        description: '点击「取消识别」后退出识别状态，回到步骤3，回显识别前的选框和选中状态。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: [
        '取消后退出识别状态并回到步骤3',
        '取消后回显进入识别前的选框和选中状态',
      ],
      source: { decisionFile, decisionObject: '取消识别', relatedFiles },
    },
    {
      id: 'BOX_STEP-008',
      title: '继续上传后自动切题提示',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '正在处理新文件提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-append-detect-tip',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-append-detect-tip'),
      display: {
        title: '继续上传后切题提示',
        description: '继续上传追加新文件后，左侧资料预览区顶部显示蓝色提示条「正在处理新文件...」，带旋转加载动画。仅在追加后切题期间显示，首次进入时和切题完成后不显示。',
        fields: ['正在处理新文件...'],
        states: ['显示：追加后切题中', '隐藏：首次切题或切题完成'],
      },
      operation: {
        title: '纯展示',
        description: '提示条不可点击、不可交互。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: [
        '追加后切题时显示',
        '首次切题不显示',
        '切题完成后消失',
      ],
      source: { decisionFile, decisionObject: '继续上传自动切题提示', relatedFiles },
    },
    {
      id: 'BOX_STEP-010',
      title: '资料预览区选框层：呈现、操作与回退状态',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'region',
      objectName: '资料预览区选框层',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-selection-layer',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-selection-layer'),
      display: {
        title: '资料选框呈现',
        description:
          '步骤3左侧资料预览区按页展示上传资料。每页资料图片上方覆盖识别框：选中框为绿色边框和浅绿色底色，左上角显示绿色圆形勾选按钮；未选中框为灰色边框和浅色底色。每个框右上角显示状态标签（待识别/识别中/已识别）、左上角显示题号标签（「第X题」或「未识别到题号」）、四角显示绿色调整手柄。用户拖拽画框时显示绿色虚线临时框。题目+答案（不同文件）模式下，资料页顶部显示「题目」或「答案」文件标签，优先展示题目文件，再展示答案文件。',
        fields: [
          '资料页图片',
          '题目文件标签',
          '答案文件标签',
          '绿色选中框',
          '灰色未选中框',
          '勾选按钮',
          '待识别标签',
          '识别中标签',
          '已识别标签',
          '题号标签',
          '未识别到题号提示',
          '删除按钮',
          '四角调整手柄',
        ],
        states: [
          '首次进入步骤3：自动切题完成后检测出的框直接显示在资料页上并默认选中',
          '题目+答案（不同文件）模式：默认只对题目文件自动切题，答案文件不自动切题',
          '答案文件手动画框：用户可在答案文件上手动画答案/解析框，未手动画时由全局答案匹配承接',
          '自动切题中：资料区显示切题加载态，切题完成后展示框',
          '未检测到内容：不显示自动框，用户可手动画框',
          '继续上传后：新文件追加到同类文件后方，新文件切出的框默认选中',
          '待识别：框正常显示并可操作，状态标签显示「待识别」',
          '识别中：参与识别的框不消失，状态标签显示「识别中」，框体不可操作',
          '已识别：原框继续显示，标签变为「已识别」并默认未选中；框未被移动或调整大小则重新选中后仍为「已识别」，否则变回「待识别」',
          '题号已识别：框内标签显示「第X题」，题号来自识别结果或用户编辑后的题号',
          '题号未识别：框内标签显示「未识别到题号」，不得按画框顺序或页面顺序推测题号',
          '步骤4返回步骤3：框选区域和右侧题目数据保留，所有框取消选中',
        ],
      },
      operation: {
        title: '资料选框操作',
        description:
          '1、用户在资料空白处按住鼠标拖动可手动画出识别框，松开后新框默认选中。\n2、点击左上角圆形勾选按钮可切换单个框的选中状态。\n3、拖动框内部可移动位置，拖动四角手柄可调整大小；跨页资料支持拖到下一页形成跨页框。\n4、点击红色删除按钮可删除单个框，也可用右侧「清空」悬浮入口删除全部框。\n5、题目+答案（不同文件）模式下，系统默认只对题目文件自动切题；答案文件不默认生成框，用户可手动画答案/解析框。\n6、点击「开始识别」时，只有当前选中的框进入识别；识别中的框不可勾选、拖动、缩放或删除，也不能新画框。\n7、识别完成后进入识别的框取消选中；用户可重新选中、移动或调整框后再次点击「开始识别」，按新范围覆盖或更新识别结果。\n8、框内题号只使用系统已获得的真实题号；未获得时显示「未识别到题号」，不得推测题号。\n9、用户未在答案文件上手动画答案/解析框时，系统继续通过全局答案匹配从答案文件中提取并关联答案。',
        permission: '无额外权限限制',
        dataFlow:
          '识别框来自自动切题结果或用户手动画框。框的位置、大小、所在页、文件角色持续保留在本流程中。开始识别时，系统读取已选中框并裁剪对应区域，识别完成后题目数据展示到右侧核对区，真实题号回写到对应框。步骤4返回步骤3时，框选区域、题号和已识别题目保留，只清空选中状态。',
        exceptions:
          '自动切题失败或未切出内容时，保留手动画框能力。题目+答案（不同文件）模式下，答案文件无手动画框不阻塞开始识别，由全局答案匹配承接。取消识别时，已框选区域不清空，识别中的框退出锁定状态恢复可操作。识别失败时保留原框和原有题号信息，右侧显示失败信息。未识别到题号时框内持续显示「未识别到题号」，直到后续识别或编辑题号后获得真实题号。',
      },
      acceptance: [
        '资料页上能看到自动切题或手动画出的识别框',
        '题目+答案（不同文件）模式下应显示题目文件和答案文件标签',
        '题目+答案（不同文件）模式下默认只对题目文件自动切题',
        '用户可在答案文件上手动画答案/解析框',
        '未手动画答案/解析框时应继续走全局答案匹配',
        '选中框和未选中框样式有明确区分',
        '单框勾选、删除、移动、缩放可用',
        '首次进入步骤3自动框默认选中',
        '继续上传后仅新增框默认选中，原有框状态保留',
        '点击开始识别后，参与识别的框不消失，显示「识别中」并不可勾选、拖动、缩放或删除',
        '识别完成后，原框继续显示为「已识别」且默认未选中',
        '已识别框可重新选中、调整并再次识别',
        '框内存在真实题号时显示「第X题」',
        '系统没有获得真实题号时显示「未识别到题号」',
        '题号不得按画框顺序、页面顺序或视觉位置推测',
        '从步骤4返回步骤3后框保留但全部不选中',
      ],
      source: {
        decisionFile,
        decisionObject: '代码补充：资料预览区选框层 / 逻辑：跨文件模式下答案文件是否参与步骤3框选 / 识别中与已识别框状态 / 题号显示规则',
        relatedFiles: [...relatedFiles, 'src/types/recognition.ts'],
      },
    },
    {
      id: 'BOX_STEP-011',
      title: '增量识别进度条（已有题目时再次点击开始识别）',
      sourceType: 'decision',
      objectType: 'region',
      objectName: '增量识别进度条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-incremental-progress',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-incremental-progress'),
      display: {
        title: '增量识别进度条',
        description: '第4步已有识别结果后，继续框选或重新框选题干时，右侧面板不再清空为全屏加载动画，而是在模式切换按钮下方显示细进度条（含加载动画、进度文案和取消按钮）。提示文案按场景区分：\n场景A（仅新增框选）：「正在识别 X 个新增区域...」\n场景B（仅重新框选已识别题目）：「正在重新识别 X 道题目...」\n场景C（混合新增+重新框选）：「正在识别 X 个区域（含 Y 道重新识别）...」\n已有题目卡片在进度条下方保持可见可滚动；被重新识别的题目卡片显示「识别中」遮罩。识别完成后进度条消失，新增或更新的题目卡片高亮闪烁。',
        fields: ['进度条', '加载动画', '场景化进度文案', '取消按钮', '已有题目卡片'],
        states: [
          '场景A：进度文案「正在识别 X 个新增区域...」，已有题目卡片正常显示可滚动',
          '场景B：进度文案「正在重新识别 X 道题目...」，被重识别的卡片半透明、中央覆盖「识别中...」标签，其余正常显示',
          '场景C：进度文案「正在识别 X 个区域（含 Y 道重新识别）...」，被重识别的卡片半透明+遮罩，其余正常显示',
          '首次识别（无已有题目）：保持原有全屏加载动画',
        ],
      },
      operation: {
        title: '增量识别流程',
        description: '1、系统自动检测选中框哪些为已识别、哪些为新增。\n2、补画漏掉题目区域：作为新增处理，按题号插入已有题目之间。\n3、重新框选已有题目：作为重新识别处理，对应卡片识别期间半透明+「识别中...」遮罩，不可操作。\n4、不受影响的题目卡片保持正常显示，可滚动查看但不可编辑。\n5、识别期间不允许编辑任何题目。\n6、取消识别后，被重识别的题目恢复旧内容，新增框选不产生新题目，进度条消失。\n7、识别完成：重识别题目恢复不透明并替换新内容，蓝色边框闪烁2.5秒；新增题目按题号插入，绿色边框闪烁2.5秒。',
        permission: '无额外权限限制',
        dataFlow: '识别结果通过 SSE 流式返回。新增题目按题号插入已有列表；同题号重识别结果替换原位置；无法获得有效题号的新增结果保留在列表末尾。',
        exceptions: '首次识别保持全屏加载动画。取消识别不丢失已有题目数据。',
      },
      acceptance: [
        '三种场景的进度文案正确显示',
        '场景B重识别卡片正确置灰+遮罩',
        '场景C混合场景两者都正确',
        '识别完成动画：新题目绿色闪烁，重识别题目蓝色闪烁',
        '暂停/取消后已有题目数据不丢失',
        '识别期间已有题目可滚动但不可编辑',
        '新增题目按题号插入已有题目之间',
        '重复题目重新识别后原位置覆盖，不新增重复卡片',
      ],
      source: {
        decisionFile,
        decisionObject: '增量识别：已有题目时再次识别的交互优化',
        relatedFiles,
      },
    },
    {
      id: 'BOX_STEP-013',
      title: '更多工具面板展开与收起规则',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'panel',
      objectName: '更多工具面板',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-more-tools',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-more-tools'),
      display: {
        title: '更多工具面板',
        description: '资料预览区右下角显示「更多工具」悬浮入口。默认收起，只显示圆形按钮和「更多工具」文字。展开后显示「更换资料」和「补充资料」两个操作项。',
        fields: ['更多工具', '更换资料', '补充资料'],
        states: [
          '默认收起：只显示入口',
          '展开状态：显示更换资料和补充资料',
          '流程切换后：默认回到收起',
          '确认弹窗打开时：面板收起',
          '30秒无操作：自动收起',
        ],
      },
      operation: {
        title: '展开与收起规则',
        description: '1、点击「更多工具」可展开或收起面板。\n2、展开后可点击「更换资料」或「补充资料」。\n3、流程切换或打开确认弹窗时，系统强制收起面板。\n4、回到步骤3时默认关闭，需手动重新展开。\n5、展开后30秒无操作自动收起。',
        permission: '无额外权限限制',
        dataFlow: '面板展开状态不影响资料、框选或识别结果数据。',
        exceptions: '触发步骤切换、确认弹窗或长时间无操作时面板自动收起。',
      },
      acceptance: [
        '默认只显示更多工具入口',
        '点击更多工具后可展开和收起面板',
        '展开后显示更换资料和补充资料',
        '流程切换时更多工具面板应收起',
        '打开任意确认弹窗时更多工具面板应收起',
        '回到步骤3时更多工具默认关闭',
        '展开后30秒无操作应自动收起',
      ],
      source: {
        decisionFile,
        decisionObject: '交互：更多工具面板缺少关闭方式 / 交互：更多工具展开状态在流程切换后的恢复规则',
        relatedFiles,
      },
    },
  ],
  excludedDecisions: [
    {
      objectName: '信息提示栏（box-step-info-bar）空壳',
      reason: '已确认直接删除空信息栏，把纵向空间还给资料预览区，不作为需求卡片展示。',
      sourceDecision: '第三轮审核 17：区域：信息提示栏（box-step-info-bar）空壳',
    },
    {
      objectName: '手动关联答案悬浮球入口与进入提示',
      reason: '手动关联答案属于步骤4「核对识别结果」内的子状态，不纳入步骤3「选择识别内容」需求卡片。',
      sourceDecision: '第三轮审核 18、22：手动关联答案仅在步骤4显示，并在进入时显示 toast',
    },
    {
      objectName: '修改识别方式 hover 触发',
      reason: '该入口属于选择识别方式返回修改规则，已由选择识别方式注册表覆盖，本页不重复生成需求卡片。',
      sourceDecision: '第三轮审核 20：修改识别方式 hover 交互保持现状',
    },
    {
      objectName: '帮助弹窗步骤3说明内容',
      reason: '已确认保持现状，本轮不新增页面级角标或悬浮说明。',
      sourceDecision: '第三轮审核 23：帮助弹窗内容不变',
    },
  ],
};
