import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
];
const decisionFile = 'docs/prd-workflow/decisions/box-recognition-step.decision.md';

const pageName = '框选识别步骤';
const route = '/homework → 识别作业资料 → 框选&识别步骤';
const moduleName = '识别作业资料';

function activateRecognizeQuestions(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到框选识别步骤', step: 'frame_and_review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

function activateFileRoleDialog() {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'openDialog' as const, label: '打开文件用途分配弹窗', dialog: 'SelectModeFileRoleDialog' },
    { type: 'scrollTo' as const, label: '定位文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
    { type: 'highlight' as const, label: '高亮文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
  ];
}

export const boxRecognitionStepRegistry: RequirementRegistry = {
  registryId: 'box-recognition-step',
  pageName,
  route,
  module: moduleName,
  description: '记录框选识别步骤页面的完整页面逻辑，覆盖统计信息栏、资料选框呈现、操作按钮、右侧空状态、文件用途弹窗、自动切题、继续/重新上传等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'BOX_STEP-001',
      title: '统计信息栏：已框选/已选中/一键清空/全选',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '框选统计信息栏',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-info-bar',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-info-bar'),
      display: {
        title: '统计信息栏',
        description: '页面左侧资料区上方显示统计信息栏。左侧为操作提示文案「若系统框选有误或漏框选，可在资料上，以按住鼠标并拖动的方式框选区域」。右侧依次显示「已框选」数字卡片（绿色大号数字）、「已选中」数字卡片（蓝色大号数字）、「一键清空」按钮（有框时可用，hover变红）、「全选」复选框。自动切题中新文件时，数字和按钮变为灰色不可操作；切题完成后恢复。',
        fields: ['已框选数字', '已选中数字', '一键清空按钮', '全选复选框', '操作提示文案'],
        states: [
          '正常态：数字高亮，按钮可操作',
          '切题中（首次）：全选 checkbox 置灰，已框选/已选中数字正常',
          '切题中（追加）：所有元素灰色，不可操作',
          '无框时：已框选和已选中均为 0，一键清空和全选置灰',
        ],
      },
      operation: {
        title: '框选统计与操作',
        description: '1、首次自动切题完成后，所有框默认选中。\n2、继续上传追加的新文件切题完成后，只默认选中新生成的框，保留原有框选状态。\n3、无框时「一键清空」和「全选」均置灰不可操作。\n4、点击「一键清空」弹出确认弹窗：「确认清空所有切题框吗？」',
        permission: '无额外权限限制',
        dataFlow: '框选数据来源于腾讯云自动切题服务或用户手动画框，选中状态影响「开始识别」按钮是否可用',
        exceptions: '自动切题失败时，原左侧显示的文案「若系统框选有误或漏框选，可在资料上，以按住鼠标并拖动的方式框选区域」，替换为「未检测到内容区域，可手动画框」',
      },
      acceptance: [
        '已框选数字正确显示',
        '已选中数字正确显示',
        '一键清空弹窗确认后可清空',
        '全选可一键选中/取消所有框',
        '切题中按钮正确置灰',
      ],
      source: { decisionFile, decisionObject: '统计信息栏', relatedFiles },
    },
    {
      id: 'BOX_STEP-002',
      title: '开始识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '开始识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-start-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-start-btn'),
      display: {
        title: '开始识别按钮',
        description: '按钮位于工具栏最右侧，当有选框选中，且无其他识别服务在进行中时，按钮高亮。按钮左侧显示当前识别方式标签（仅识别题目/识别题目和答案）。按钮文案为「开始识别」，有选中框时显示数量如「开始识别(3)」。',
        fields: ['开始识别', '选中数量', '识别方式标签'],
        states: [
          '可用态：有选中框且不在处理中 → 绿色背景白色文字',
          '禁用态：无选中框、正在处理中或自动切题中 → 灰色背景灰色文字不可点击',
          'review步骤：识别方式标签半透明（opacity-50）',
        ],
      },
      operation: {
        title: '开始识别',
        description: '1、点击「开始识别」后，系统根据已选中的框裁剪对应图片区域，调用 AI 进行题目内容识别。\n2、仅识别题目模式下，所有框按题目框处理，右边只展示题干。\n3、识别题目和答案模式下，题目框走完整识别流程，答案框走答案提取流程，右边展示题干+答案/解析。\n4、自动切题完成且有框时默认全选，按钮自动可用；无框时按钮置灰。',
        permission: '无额外权限限制',
        dataFlow: '将已选中的框、裁剪后的图片、识别模式和学科信息发送给 AI 识别服务',
        exceptions: '识别过程中显示「暂停识别」和「取消识别」按钮。暂停后可继续，取消后保留框选状态不变仅终止识别。识别失败时保留已有框选，右侧显示错误信息。',
      },
      acceptance: [
        '有选中框时按钮可用',
        '无选中框时按钮置灰',
        '切题中按钮置灰',
        '识别方式标签正确显示',
        '点击后进入识别流程',
      ],
      source: { decisionFile, decisionObject: '开始识别按钮', relatedFiles },
    },
    {
      id: 'BOX_STEP-003',
      title: '右侧空状态引导',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '右侧空状态引导文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-empty-state',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-empty-state'),
      display: {
        title: '右侧空状态',
        description: '点击开始识别前，右侧面板显示空状态引导。仅识别题目模式文案：「框选题目并选中后，点击「开始识别」，小乐会自动为您识别题目，完成识别后，您可在右侧以图片或文字的形式分模块查看每道题目」。识别题目和答案模式文案：「框选题目并选中后，点击「开始识别」，小乐会为您自动识别题目，并进行题目和答案的自动匹配。完成识别后，您可在右侧以图片或文字的形式分模块查看每道题的题干与答案/解析」。有选中框时下方显示「已选中 X 个识别框」。',
        fields: ['空状态引导文案', '已选中 X 个识别框'],
        states: ['空态（无题目卡片）', '有选中框时显示已选中数量'],
      },
      operation: {
        title: '纯展示',
        description: '引导文案和已选中数量为纯展示，不可交互。仅用于帮助用户理解下一步操作。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['两种模式文案不同', '已选中数量正确', '与操作按钮状态一致'],
      source: { decisionFile, decisionObject: '右侧面板空态说明', relatedFiles },
    },
    {
      id: 'BOX_STEP-004',
      title: '文件用途分配弹窗（识别题目和答案模式）',
      sourceType: 'code+decision',
      objectType: 'dialog',
      objectName: '文件用途分配弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-role-dialog',
      anchorStatus: 'implemented',
      activate: activateFileRoleDialog(),
      display: {
        title: '文件用途分配弹窗',
        description: '当用户在步骤1选择的是识别题目和答案模式，进入到步骤2之后，用户又点击继续上传，完成文件上传后，弹出「指定文件用途」弹窗。每份文件显示名称和「题目文件」「答案文件」两个按钮。底部有「取消」和「确认，开始处理」按钮。当用户在步骤1只上传了一份文件，且选择的是识别题目和答案模式，进入到步骤2后，用户又点击继续上传，完成文件上传后，弹出的「指定文件用途」弹窗，显示的提示文案为「检测到你上传了X个文件，请指定文件用途」；当用户在步骤1只上传了多份文件，且选择的是识别题目和答案模式，进入到步骤2后，用户又点击继续上传，完成文件上传后，弹出的「指定文件用途」弹窗，显示的提示文案为「检测到你新上传了X个文件，请指定文件用途」。',
        fields: ['文件名', '题目文件按钮', '答案文件按钮'],
        states: [
          '首次弹出：显示全部文件，说明文案为「检测到您上传了 X 个文件，请分别指定用途」',
          '继续上传后（已有文件已分配文件用途）：仅显示新增文件，说明文案为「检测到您新增了 X 个文件，请分别为新增文件指定用途」',
          '文件用途选中态：绿色高亮',
          '确认按钮：所有文件分配后可用',
        ],
      },
      operation: {
        title: '文件用途分配',
        description: '1、每份文件独立选择文件用途，互不影响。\n2、点击已选中的文件用途按钮可取消选择，恢复为未分配状态。\n3、所有文件都分配文件用途后，「确认，开始处理」按钮高亮可点击。\n4、点击确认后进入框选识别页面。\n5、取消或✕关闭弹窗，同时取消已选的识别模式。',
        permission: '无额外权限限制',
        dataFlow: '文件用途分配结果传递给后续流程，决定文件标签切换和显示顺序',
        exceptions: '关闭弹窗时如有未分配文件，直接关闭不提示',
      },
      acceptance: [
        '文件独立选择文件用途',
        '点击已选可取消',
        '继续上传后仅显示新文件',
        '文案按场景正确切换',
      ],
      source: { decisionFile, decisionObject: '文件用途分配弹窗', relatedFiles },
    },
    {
      id: 'BOX_STEP-005',
      title: '继续上传按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '继续上传按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-continue-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-continue-btn'),
      display: {
        title: '继续上传按钮',
        description: '按钮位于工具栏，绿色文字样式。悬停提示「继续上传资料」。',
        fields: ['继续上传'],
        states: [
          '正常态：绿色文字可点击',
          '自动切题中：灰色文字不可点击，悬停提示「正在处理文件，请稍后再继续上传」',
        ],
      },
      operation: {
        title: '继续上传',
        description: '1、点击继续上传后，打开文件选择弹窗，允许追加新文件。\n2、仅识别题目模式：追加后直接开始切题，不弹任何弹窗。\n3、识别题目和答案模式：追加后如有新文件形成多文件场景，弹出文件用途分配弹窗。\n4、追加后保留已有框选和选中状态，仅对新页面自动切题。\n5、自动切题中不允许继续上传，点击时显示提示文案。',
        permission: '无额外权限限制',
        dataFlow: '新文件追加到现有文件列表末尾',
        exceptions: '正在处理文件时点击，临时显示「正在处理文件，请稍后再继续上传」3秒后消失',
      },
      acceptance: [
        'single模式不弹窗',
        'stepwise模式弹文件用途弹窗',
        '切题中置灰不可点击',
        '已有框选保留',
      ],
      source: { decisionFile, decisionObject: '继续上传', relatedFiles },
    },
    {
      id: 'BOX_STEP-006',
      title: '重新上传按钮与确认弹窗',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '重新上传按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-reupload-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-reupload-btn'),
      display: {
        title: '重新上传按钮',
        description: '按钮位于继续上传按钮左侧，灰色文字样式。点击弹出确认弹窗：「重新上传将清空当前资料、框选和识别方式，是否继续？」。弹窗有「取消」和「确认」按钮。',
        fields: ['重新上传', '确认弹窗'],
        states: ['正常态：灰色文字可点击', 'review步骤隐藏'],
      },
      operation: {
        title: '重新上传',
        description: '1、点击重新上传弹出确认弹窗。\n2、确认后清空所有数据（框选、识别模式、文件用途、识别结果），关闭当前弹窗回到主页上传文件的弹窗页面（AI小乐面板为弹窗背景的页面）。\n3、用户可直接进行上传文件的操作，无需再点击AI小乐面板里的「帮我识别作业资料」的快捷按钮。',
        permission: '无额外权限限制',
        dataFlow: '确认后清空所有流程数据，关闭弹窗',
        exceptions: '确认弹窗可取消，取消后保持当前状态不变',
      },
      acceptance: [
        '点击弹出确认弹窗',
        '确认后回到主页',
        '取消保持当前状态',
        'review步骤不显示',
      ],
      source: { decisionFile, decisionObject: '重新上传', relatedFiles },
    },
    {
      id: 'BOX_STEP-007',
      title: '暂停/取消识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '暂停识别/取消识别/继续识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-pause-cancel-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-pause-cancel-btn'),
      display: {
        title: '识别过程控制按钮',
        description: '点击开始识别后，右侧面板显示进度提示和两个控制按钮。「暂停识别」（橙色）点击后变为「继续识别」（绿色），spinner停止旋转。「取消识别」（灰色）始终可见。',
        fields: ['暂停识别', '继续识别', '取消识别'],
        states: [
          '进行中：显示「暂停识别」+「取消识别」',
          '已暂停：显示「继续识别」+「取消识别」，spinner静止',
        ],
      },
      operation: {
        title: '暂停/取消识别',
        description: '1、点击「暂停识别」后，中止当前识别请求，暂停右侧处理状态，按钮变为「继续识别」。\n2、点击「继续识别」后，重新提交识别请求，从暂停处继续。\n3、点击「取消识别」后，中止识别请求，保留左侧框选和选中状态不变，仅终止本次识别操作。',
        permission: '无额外权限限制',
        dataFlow: '暂停时保留已识别的部分结果，继续时重新提交',
        exceptions: '暂停后不创建模拟数据，不清除已有结果',
      },
      acceptance: [
        '暂停按钮切换为继续',
        '暂停时spinner停止',
        '取消保留框选状态',
      ],
      source: { decisionFile, decisionObject: '暂停识别/取消识别', relatedFiles },
    },
    {
      id: 'BOX_STEP-008',
      title: '继续上传后自动切题提示',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '正在处理新文件提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-append-detect-tip',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-append-detect-tip'),
      display: {
        title: '继续上传后切题提示',
        description: '继续上传追加新文件后，左侧资料预览区顶部显示蓝色提示条「正在处理新文件...」，带有旋转加载动画。提示条仅在追加后的自动切题期间显示（已有框 + 正在切题中），首次进入页面切题时不显示。切题完成后自动消失。',
        fields: ['正在处理新文件...'],
        states: ['显示：追加后切题中', '隐藏：首次切题或切题完成'],
      },
      operation: {
        title: '纯展示',
        description: '提示条为纯展示，仅用于告知用户系统正在处理新追加的文件。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: [
        '追加后切题时显示',
        '首次切题不显示',
        '切题完成后消失',
      ],
      source: { decisionFile, decisionObject: '继续上传自动切题提示', relatedFiles },
    },
    {
      id: 'BOX_STEP-009',
      title: '操作提示文案',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '框选操作提示文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-hint-text',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-hint-text'),
      display: {
        title: '操作提示文案',
        description: '统计信息栏左侧显示「若系统框选有误或漏框选，可在资料上，以按住鼠标并拖动的方式框选区域」。灰色小字，始终可见。',
        fields: ['框选操作提示'],
        states: ['正常显示'],
      },
      operation: {
        title: '纯展示',
        description: '操作提示为纯展示文案，不需要用户交互。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['文案正确显示'],
      source: { decisionFile, decisionObject: '操作提示', relatedFiles },
    },
    {
      id: 'BOX_STEP-010',
      title: '资料预览区选框层：呈现、操作与回退状态',
      sourceType: 'code',
      objectType: 'region',
      objectName: '资料预览区选框层',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-selection-layer',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-selection-layer'),
      display: {
        title: '资料选框呈现',
        description: '步骤2「选择识别内容」中，左侧资料预览区按页展示上传资料。每页右上角显示「本页 X 框 / 共 Y 框」。自动切题或手动画出的识别框覆盖在资料图片上：选中框为绿色边框和浅绿色底色，左上角显示绿色圆形勾选按钮；未选中框为灰色边框和浅色底色；未识别框右上角显示黄色「待识别」标签和红色删除按钮。每个框四角显示绿色调整手柄；跨页框显示「↓ 跨页」或「跨页续 ↑」提示；用户正在拖拽画框时，页面上显示绿色虚线临时框。',
        fields: [
          '资料页图片',
          '本页框数提示',
          '绿色选中框',
          '灰色未选中框',
          '勾选按钮',
          '待识别标签',
          '删除按钮',
          '四角调整手柄',
          '跨页提示',
        ],
        states: [
          '首次进入步骤2：资料处理完成后自动切题，检测出的框直接显示在对应资料页上并默认选中',
          '自动切题中：资料区显示切题进度，切题完成后再展示框',
          '未检测到内容区域：不显示自动框，用户仍可在资料上手动画框',
          '继续上传后：原有框保留在原页，新文件切出的框追加到新页并默认选中',
          '识别完成后返回步骤2：已框选区域和右侧题目数据保留，所有框取消选中，用户可重新选择、调整或再次识别',
        ],
      },
      operation: {
        title: '资料选框操作',
        description: '1、用户在资料空白处按住鼠标并拖动，可手动画出识别框，松开后新框默认选中。\n2、用户可点击左上角圆形勾选按钮切换单个框是否参与识别，也可用统计栏「全选」一次性切换所有框。\n3、用户可拖动框内部移动位置，拖动四角手柄调整大小；跨页资料支持从当前页拖到下一页形成跨页框。\n4、用户可点击红色删除按钮删除单个框，也可用统计栏「一键清空」删除全部框。\n5、点击「开始识别」时，只有当前选中的框进入识别；已识别框如果被重新选中并调整，会按新范围重新识别。',
        permission: '无额外权限限制',
        dataFlow: '识别框来自自动切题结果或用户手动画框。框的位置、大小、所在页、选中状态和识别状态会持续留在本次识别流程中；开始识别时，系统只读取已选中的框并裁剪对应资料区域，识别完成后把题目数据展示到右侧核对区，同时取消已识别框的选中状态。用户从步骤3返回步骤2时，框选区域和已识别题目继续保留，只清空选中状态，便于重新选择或调整后再次识别。',
        exceptions: '自动切题失败或未切出内容时，页面保留手动画框能力；用户取消识别时，已框选区域和选中状态不被清空；用户删除单个框或一键清空后，对应框不再参与后续识别。',
      },
      acceptance: [
        '资料页上能看到自动切题或手动画出的识别框',
        '选中框和未选中框样式有明确区分',
        '单框勾选、删除、移动、缩放可用',
        '跨页框显示跨页提示',
        '首次进入步骤2自动框默认选中',
        '继续上传后仅新增框默认选中，原有框状态保留',
        '从步骤3返回步骤2后框保留但全部不选中',
      ],
      source: {
        decisionFile,
        decisionObject: '代码补充：资料预览区选框层',
        relatedFiles: [...relatedFiles, 'src/types/recognition.ts'],
      },
    },
    {
      id: 'BOX_STEP-011',
      title: '增量识别进度条（已有题目时再次点击开始识别）',
      sourceType: 'decision',
      objectType: 'region',
      objectName: '增量识别进度条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-incremental-progress',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-incremental-progress'),
      display: {
        title: '增量识别进度条',
        description: '当用户已有一部分识别完成的题目、再次回到步骤2框选新区域并点击「开始识别」后，右侧面板不再清空为全屏加载动画，而是在模式切换按钮下方显示一条细进度条。进度条高度约36px，包含加载动画、进度文案和暂停/取消按钮。进度条上的提示文案，按场景分类展示，共有三种场景，分别如下：\n场景A（仅新增框选）：「正在识别 X 个新增区域...」\n场景B（仅重新框选已识别题目）：「正在重新识别 X 道题目...」\n场景C（混合新增+重新框选）：「正在识别 X 个区域（含 Y 道重新识别）...」\n已有的题目卡片在进度条下方保持可见可滚动，仅受影响的题目卡片显示「识别中」遮罩。识别完成后进度条自动消失，新增或更新的题目卡片高亮闪烁。',
        fields: ['进度条', '加载动画', '场景化进度文案', '暂停按钮', '取消按钮', '已有题目卡片'],
        states: [
          '场景A（仅新增框选）：进度文案「正在识别 X 个新增区域...」，已有题目卡片全部正常显示可滚动',
          '场景B（仅重新框选已识别题目）：进度文案「正在重新识别 X 道题目...」，被重新识别的题目卡片变为半透明+不可操作，中央覆盖「识别中...」标签，其余题目正常显示',
          '场景C（混合新增+重新框选）：进度文案「正在识别 X 个区域（含 Y 道重新识别）...」，被重新识别的题目卡片半透明+「识别中...」遮罩，其余题目正常显示，新增题目识别完成后插入列表',
          '首次识别（无已有题目）：保持原有的全屏加载动画不变',
        ],
      },
      operation: {
        title: '增量识别流程',
        description: '1、系统自动检测本次选中的框哪些是已识别过的（通过框ID、题号、位置匹配），哪些是新增的。\n2、已识别过被重新框选的题目，其卡片在识别期间变为半透明（opacity-40），中央覆盖「识别中...」标签，不可操作，原识别内容隐藏。\n3、不受本次识别影响的题目卡片保持正常显示，用户可滚动查看、切换图片/编辑模式。\n4、识别期间不允许编辑任何题目内容。\n5、暂停后所有状态保持，已识别题目卡片继续可见。\n6、取消识别后，被重新识别的题目恢复回识别前的旧内容，新增的框选不产生新题目，进度条消失。\n7、识别完成后：重新识别的题目卡片恢复不透明并替换为新内容，蓝色边框+脉冲动画闪烁2.5秒；新增题目按题号插入列表，绿色边框+脉冲动画闪烁2.5秒。',
        permission: '无额外权限限制',
        dataFlow: '识别结果通过SSE流式返回，新增题目插入已有题目列表末尾，重新识别的题目替换原题目的内容、答案和解析',
        exceptions: '首次识别（无已有题目）时保持原有全屏加载动画；进度条文案根据三种场景自动区分；暂停/取消不丢失已有题目数据',
      },
      acceptance: [
        '三种场景的进度文案正确显示',
        '场景B重识别卡片正确置灰+遮罩',
        '场景C混合场景两者都正确',
        '识别完成动画：新题目绿色闪烁，重识别题目蓝色闪烁',
        '暂停/取消后已有题目数据不丢失',
        '识别期间已有题目可滚动但不可编辑',
      ],
      source: {
        decisionFile,
        decisionObject: '增量识别：已有题目时再次识别的交互优化',
        relatedFiles,
      },
    },
  ],
  excludedDecisions: [],
};
