import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
];
const decisionFile = '产品文档/prd-workflow/decisions/box-recognition-step.decision.md';

const pageName = '选择识别内容';
const route = '/homework → 识别作业资料 → 选择识别内容';
const moduleName = '识别作业资料';

function activateRecognizeQuestions(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到选择识别内容', step: 'frame_and_review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

function activateMoreTools(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到选择识别内容', step: 'frame_and_review' },
    { type: 'openPanel' as const, label: '展开更多工具菜单', panel: 'BoxStepMoreTools' },
    { type: 'scrollTo' as const, label: '定位更多工具入口', anchorId },
    { type: 'highlight' as const, label: '高亮更多工具入口', anchorId },
  ];
}

function activateFileRoleDialog() {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'openDialog' as const, label: '打开文件用途分配弹窗', dialog: 'SelectModeFileRoleDialog' },
    { type: 'scrollTo' as const, label: '定位文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
    { type: 'highlight' as const, label: '高亮文件用途分配弹窗', anchorId: 'select-mode-file-role-dialog' },
  ];
}

export const boxRecognitionStepRegistry: RequirementRegistry = {
  registryId: 'box-recognition-step',
  pageName,
  route,
  module: moduleName,
  description: '记录步骤 3「选择识别内容」的完整页面逻辑，覆盖资料选框呈现、右侧悬浮操作、右侧空状态、文件用途弹窗、自动切题、补充资料、修改资料、重新上传和增量识别等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'BOX_STEP-001',
      title: '框选统计信息',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'region',
      objectName: '已选中/已框选统计文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-selection-stats',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-selection-stats'),
      display: {
        title: '框选统计信息',
        description: '资料预览区右上角显示当前框选统计文案「已选中 X 题 / 已框选 Y 题」。统计文案以深色悬浮信息条呈现，帮助用户判断当前有多少识别框、其中多少会参与本次识别。',
        fields: ['已选中 X 题', '已框选 Y 题'],
        states: [
          '正常态：自动切题完成或用户手动画框后，资料页右上角显示已选中数量和已框选数量',
          '无框时：已选中和已框选均显示为 0',
          '框选变化时：用户新增、删除或切换识别框选中状态后，统计数字同步变化',
          '切题中（首次）：资料区显示切题加载态，右侧悬浮操作暂不显示',
          '切题中（追加）：新增资料切题期间，右侧悬浮操作正常显示（因为新增资料切题期间，原本已切好的资料信息还在）',
        ],
      },
      operation: {
        title: '统计随框选状态刷新',
        description: '统计文案不可点击。用户新增、删除或勾选识别框后，页面同步刷新已选中和已框选数量；「开始识别」按钮根据已选中数量判断是否可用。',
        permission: '无额外权限限制',
        dataFlow: '统计数据来源于当前资料页的识别框和选中状态，用于提示本次将进入识别的范围。',
        exceptions: '自动切题未检测到内容时，统计保持为 0；用户仍可手动画框后再刷新统计。',
      },
      acceptance: [
        '已框选数字正确显示',
        '已选中数字正确显示',
        '统计角标应显示在统计文案旁边',
        '统计角标不应挂在清空按钮上',
        '无框时两个数字均显示为 0',
      ],
      source: { decisionFile, decisionObject: '框选统计信息', relatedFiles },
    },
    {
      id: 'BOX_STEP-014',
      title: '清空框选操作',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '清空框选悬浮球',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-clear-action',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-clear-action'),
      display: {
        title: '清空框选入口',
        description: '步骤 3「选择识别内容」中，资料预览区右侧中部在「开始识别」下方显示清空圆形图标按钮和文字按钮「清空」。有可操作识别框时，按钮以红色可点击状态展示；没有可操作识别框、正在切题，按钮置灰不可点击。点击开始识别后，按钮隐藏。',
        fields: ['清空圆形图标按钮', '清空文字按钮'],
        states: [
          '可用态：当前存在可操作识别框时，清空按钮红色展示并可点击',
          '禁用态：没有可操作识别框、正在切题时，清空按钮置灰不可点击',
          '核对识别结果步骤：清空入口隐藏',
        ],
      },
      operation: {
        title: '清空框选',
        description: '1、用户点击「清空」后，弹出确认弹窗「确认清空所有切题框吗？」。\n2、用户确认后，系统删除当前选择识别内容步骤中的全部框选区域，并清空当前选中状态。\n3、用户取消确认时，已有框选区域和选中状态保持不变。\n4、清空完成后，已选中和已框选统计归零，「开始识别」按钮变为不可点击。',
        permission: '无额外权限限制',
        dataFlow: '清空操作只处理当前识别任务中的框选区域和选中状态，不删除已上传资料。',
        exceptions: '没有可操作识别框时，清空按钮置灰，不弹出确认弹窗。',
      },
      acceptance: [
        '清空需求角标应显示在清空悬浮球旁边',
        '有可操作识别框时清空按钮可点击',
        '无可操作识别框时清空按钮置灰',
        '点击清空应先弹出确认弹窗',
        '确认后已选中和已框选数量归零',
      ],
      source: { decisionFile, decisionObject: '清空框选操作', relatedFiles },
    },
    {
      id: 'BOX_STEP-002',
      title: '开始识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '开始识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-start-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-start-btn'),
      display: {
        title: '开始识别按钮',
        description: '按钮位于资料预览区右侧中部，以绿色圆形悬浮球和下方「开始识别」文字按钮呈现。第 3 步有选框选中时可点击，点击后进入第 4 步「核对识别结果」并开始识别；第 4 步核对结果时，左侧资料区仍可继续新增框选或重新框选已有题干，存在选中框时该按钮继续可用。无选中框或处理中时置灰不可点击。',
        fields: ['开始识别悬浮球', '开始识别文字按钮', '选中数量'],
        states: [
          '可用态：有选中框且不在处理中 → 绿色背景白色文字',
          '禁用态：无选中框、正在处理中 → 灰色背景灰色文字不可点击',
        ],
      },
      operation: {
        title: '开始识别',
        description: '1、点击「开始识别」后，系统根据已选中的框裁剪对应图片区域，调用 AI 进行题目内容识别，并进入第 4 步「核对识别结果」。\n2、仅识别题目模式下，所有框按题目框处理，右边只展示题干。\n3、识别题目和答案模式下，题目框走完整识别流程，答案框走答案提取流程，右边展示题干+答案/解析。\n4、自动切题完成且有框时默认选中识别框，按钮自动可用；无框时，或有框但无框选中时，按钮置灰。\n5、第 4 步核对时，如果用户发现漏识别题目，可在左侧资料区新增框选后再次点击「开始识别」，识别结果按题号进入右侧核对列表。\n6、第 4 步核对时，如果用户发现已有题干不完整，可重新框选同一道题更完整的题干范围后再次点击「开始识别」；识别完成后，同题号结果覆盖原题卡，不新增重复题卡。',
        permission: '无额外权限限制',
        dataFlow: '将已选中的框、裁剪后的图片、识别模式和学科信息发送给 AI 识别服务',
        exceptions: '识别过程中显示「取消识别」按钮。点击取消识别，则退出识别状态，回到步骤3，并且回显进入识别的选框和选框的选中状态。识别失败时保留原来的选框以及选框的选中状态，右侧显示错误信息。',
      },
      acceptance: [
        '有选中框时按钮可用',
        '无选中框时按钮置灰',
        '切题中按钮置灰',
        '识别方式标签正确显示',
        '点击后进入识别流程',
        '第4步新增框选后可继续点击开始识别',
        '第4步重复框选同题号题干后应覆盖原题卡',
      ],
      source: { decisionFile, decisionObject: '开始识别按钮', relatedFiles },
    },
    {
      id: 'BOX_STEP-003',
      title: '右侧空状态引导',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '右侧空状态引导文案',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-empty-state',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-empty-state'),
      display: {
        title: '右侧空状态',
        description: '点击开始识别前，右侧面板显示空状态引导。仅识别题目模式文案：「框选题目并选中后，点击「开始识别」，小乐会自动为您识别题目，完成识别后，您可在右侧以图片或文字的形式分模块查看每道题目」。识别题目和答案模式文案：「框选题目并选中后，点击「开始识别」，小乐会为您自动识别题目，并进行题目和答案的自动匹配。完成识别后，您可在右侧以图片或文字的形式分模块查看每道题的题干与答案/解析」。有选中框时下方显示「已选中 X 个识别框」。',
        fields: ['空状态引导文案', '已选中 X 个识别框'],
        states: ['空态（无题目卡片）', '有选中框时显示已选中数量'],
      },
      operation: {
        title: '纯展示',
        description: '引导文案和已选中数量为纯展示，不可交互。仅用于帮助用户理解下一步操作。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['两种模式文案不同', '已选中数量正确', '与操作按钮状态一致'],
      source: { decisionFile, decisionObject: '右侧面板空态说明', relatedFiles },
    },
    {
      id: 'BOX_STEP-004',
      title: '文件用途分配弹窗（识别题目和答案模式）',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'dialog',
      objectName: '文件用途分配弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-role-dialog',
      anchorStatus: 'implemented',
      activate: activateFileRoleDialog(),
      display: {
        title: '文件用途分配弹窗',
        description: '当用户在「题目+答案（不同文件）」模式下补充资料，且新增文件需要指定用途时，页面显示「指定文件用途」弹窗。弹窗展示新增文件说明、文件列表、每份文件的「题目文件」「答案文件」按钮，以及底部「取消」和「确认，开始处理」按钮。在步骤3，如果用户补充上传了资料，且识别模式选择的是题目+答案（不同文件），那完成文件上传后，也需要显示该弹窗，为新上传的文件指定用途。',
        fields: ['指定文件用途', '文件名', '题目文件按钮', '答案文件按钮', '取消', '确认，开始处理'],
        states: [
          '补充资料后弹出：仅显示本次新增文件，说明文案为「检测到您新增了 X 个文件，请分别为新增文件指定用途」',
          '文件用途选中态：绿色高亮',
          '确认按钮：所有文件分配后可用',
          '确认按钮禁用态：存在未分配用途的文件时不可点击',
        ],
      },
      operation: {
        title: '文件用途分配',
        description: '1、每份文件独立选择文件用途，互不影响。\n2、点击已选中的文件用途按钮可取消选择，恢复为未分配状态。\n3、所有文件都分配文件用途后，「确认，开始处理」按钮高亮可点击。\n4、点击确认后，新增文件按用途进入当前识别流程。\n5、取消或关闭弹窗时，系统撤回本次新补充文件。',
        permission: '无额外权限限制',
        dataFlow: '文件用途分配结果传递给后续流程，决定新增文件在资料预览区的题目/答案标签、显示顺序、自动切题范围和后续答案匹配范围。',
        exceptions: '步骤3补充资料后，用户取消或关闭文件用途分配弹窗时，系统撤回本次新补充文件，并提示「已取消本次补充资料」；原有框选和识别结果保持不变。',
      },
      acceptance: [
        '文件独立选择文件用途',
        '点击已选可取消',
        '补充资料后仅显示本次新增文件',
        '文案按场景正确切换',
        '取消或关闭弹窗后应撤回本次新补充文件',
        '取消或关闭弹窗后应提示「已取消本次补充资料」',
        '取消或关闭弹窗后原有框选和识别结果应保持不变',
      ],
      source: { decisionFile, decisionObject: '文件用途分配弹窗 / 交互：补充资料后文件用途弹窗取消/关闭的处理', relatedFiles },
    },
    {
      id: 'BOX_STEP-005',
      title: '补充资料入口',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '补充资料按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-supplement-upload',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-supplement-upload'),
      display: {
        title: '补充资料按钮',
        description: '步骤3「选择识别内容」中，资料预览区右下角展示「更多工具」悬浮入口。展开后显示「补充资料」按钮，按钮使用绿色文字和上传图标。该入口只用于补充本地资料，不展示资源库入口。',
        fields: ['更多工具', '补充资料'],
        states: [
          '更多工具未展开：仅显示悬浮入口',
          '更多工具已展开：显示补充资料按钮',
          '资料选择弹窗：隐藏资源库 Tab',
        ],
      },
      operation: {
        title: '补充资料',
        description: '1、点击「补充资料」后，打开资料选择弹窗，只保留本地上传入口。\n2、仅识别题目模式和题目+答案（同文件）模式下，补充资料上传后直接对新增资料自动切题。\n3、题目+答案（不同文件）模式下，补充资料上传后，新增文件需要分配用途；完成文件上传后，也需要显示文件用途分配弹窗，为新上传的文件指定用途。\n4、补充资料后保留已有框选和选中状态，仅对新页面自动切题。\n5、如果用户取消或关闭补充资料后的文件用途分配弹窗，系统撤回本次新补充文件。',
        permission: '无额外权限限制',
        dataFlow: '本地新文件追加到现有文件列表末尾；系统以最新资料列表继续生成框选结果，已有框选和识别结果不因补充资料被清空。若补充资料后的用途分配被取消，本次新增文件从当前任务中撤回。',
        exceptions: '取消或关闭补充资料后的文件用途分配弹窗时，提示「已取消本次补充资料」。',
      },
      acceptance: [
        '更多工具展开后显示补充资料入口',
        '补充资料入口打开资料选择弹窗时隐藏资源库 Tab',
        '仅识别题目模式不弹文件用途分配弹窗',
        '题目+答案（同文件）模式不弹文件用途分配弹窗',
        '题目+答案（不同文件）模式按文件用途规则弹窗',
        '取消文件用途分配后应撤回本次补充文件',
        '已有框选保留',
      ],
      source: { decisionFile, decisionObject: '按钮：更多工具里的「补充资料」资料来源范围 / 交互：补充资料后文件用途弹窗取消/关闭的处理', relatedFiles },
    },
    {
      id: 'BOX_STEP-012',
      title: '修改资料入口与清空确认',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '修改资料按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-modify-files',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-modify-files'),
      display: {
        title: '修改资料入口与确认弹窗',
        description: '步骤3「选择识别内容」中，资料预览区右下角展示「更多工具」悬浮入口。展开后显示「修改资料」按钮；当前已有识别结果时，点击后弹出确认弹窗，显示提示文案「确认修改资料吗？修改资料，将清空当前已识别的内容，并且需要重新选择识别方式。」',
        fields: ['更多工具', '修改资料', '确认修改资料吗？', '取消', '确认'],
        states: ['更多工具未展开', '更多工具已展开', '无识别结果', '已有识别结果', '确认弹窗打开状态'],
      },
      operation: {
        title: '返回上传资料步骤',
        description: '1、用户点击「修改资料」后，更多工具面板先收起，再返回步骤1「上传资料」管理本次资料。\n2、已有识别结果时，系统先提示用户确认清理当前题目和框选结果；用户确认后再返回。\n3、无识别结果时，直接返回步骤1。\n4、点击修改资料返回第一步之后，继续回显之前已经上传过的资料，和对应资料选择的要识别的范围。\n5、确认返回后，用户后续执行删除、调整识别范围或继续上传，均按最新资料列表重新处理。',
        permission: '无额外权限限制',
        dataFlow: '确认后清空题目、答案、框选、文件用途和识别方式，保留当前资料和对应识别范围供用户继续管理。',
        exceptions: '用户取消确认时，保持当前步骤和识别结果不变；打开确认弹窗时「更多工具」面板应收起；连续修改资料时，不得使用过期文件列表生成后续结果。',
      },
      acceptance: [
        '更多工具展开后显示修改资料入口',
        '点击修改资料后更多工具面板应收起',
        '已有识别结果时点击修改资料应先展示清空提示',
        '确认后应返回上传资料步骤并清理当前识别进度',
        '返回上传资料步骤后应回显已上传资料和对应识别范围',
        '无识别结果时可直接返回上传资料步骤',
        '取消后应保持当前步骤和已有识别结果',
      ],
      source: {
        decisionFile: '产品文档/prd-workflow/decisions/upload-files-step.decision.md',
        decisionObject: '交互：返回「上传资料」的入口 / 逻辑：修改资料后的重算范围 / 状态：资料重新处理期间的页面操作 / 交互：更多工具展开状态在流程切换后的恢复规则',
        relatedFiles,
      },
    },
    {
      id: 'BOX_STEP-006',
      title: '重新上传按钮与确认弹窗',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '重新上传按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-reupload-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-reupload-btn'),
      display: {
        title: '重新上传按钮',
        description: '按钮位于继续上传按钮左侧，灰色文字样式。点击弹出确认弹窗：「确认修改资料吗？修改资料，将清空当前已有的识别结果。」弹窗有「取消」和「确认」按钮。',
        fields: ['重新上传', '确认弹窗'],
        states: ['正常态：灰色文字可点击', '核对识别结果步骤隐藏'],
      },
      operation: {
        title: '重新上传',
        description: '1、点击重新上传弹出确认弹窗。\n2、确认后清空所有数据（框选、识别模式、文件用途、识别结果），关闭当前弹窗步骤1的页面，回显之前已经上传的文件，和选择识别范围。',
        permission: '无额外权限限制',
        dataFlow: '确认后清空框选、识别模式、文件用途和识别结果，回到步骤1并回显之前已上传的文件和识别范围。',
        exceptions: '确认弹窗可取消，取消后保持当前状态不变',
      },
      acceptance: [
        '点击弹出确认弹窗',
        '确认后回到步骤1并回显已上传文件和识别范围',
        '取消保持当前状态',
        '核对识别结果步骤不显示',
      ],
      source: { decisionFile, decisionObject: '重新上传', relatedFiles },
    },
    {
      id: 'BOX_STEP-007',
      title: '取消识别按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '取消识别按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-pause-cancel-btn',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-pause-cancel-btn'),
      display: {
        title: '取消识别按钮',
        description: '点击开始识别后，右侧面板显示进度提示和「取消识别」按钮。「取消识别」（灰色）始终可见。',
        fields: ['取消识别'],
        states: ['识别中：显示「取消识别」'],
      },
      operation: {
        title: '取消识别',
        description: '1、点击「取消识别」后，退出识别状态，回到步骤3，并且回显进入识别的选框和选框的选中状态。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: [
        '取消后退出识别状态并回到步骤3',
        '取消后回显进入识别前的选框和选中状态',
      ],
      source: { decisionFile, decisionObject: '取消识别', relatedFiles },
    },
    {
      id: 'BOX_STEP-008',
      title: '继续上传后自动切题提示',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '正在处理新文件提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-append-detect-tip',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-append-detect-tip'),
      display: {
        title: '继续上传后切题提示',
        description: '继续上传追加新文件后，左侧资料预览区顶部显示蓝色提示条「正在处理新文件...」，带有旋转加载动画。提示条仅在追加后的自动切题期间显示（已有框 + 正在切题中），首次进入页面切题时不显示。切题完成后自动消失。',
        fields: ['正在处理新文件...'],
        states: ['显示：追加后切题中', '隐藏：首次切题或切题完成'],
      },
      operation: {
        title: '纯展示',
        description: '提示条为纯展示，仅用于告知用户系统正在处理新追加的文件。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: [
        '追加后切题时显示',
        '首次切题不显示',
        '切题完成后消失',
      ],
      source: { decisionFile, decisionObject: '继续上传自动切题提示', relatedFiles },
    },
    {
      id: 'BOX_STEP-010',
      title: '资料预览区选框层：呈现、操作与回退状态',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'region',
      objectName: '资料预览区选框层',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-selection-layer',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-selection-layer'),
      display: {
        title: '资料选框呈现',
        description: '步骤3「选择识别内容」中，左侧资料预览区按页展示上传资料。每页右上角显示当前可见框选统计。题目+答案（不同文件）模式下，资料页顶部显示「题目」或「答案」文件标签，显示的依据为用户在上一步，为文件指定的用途类型，显示的顺序为，优先显示题目文件，待题目文件显示完之后，再在资料页区域显示答案文件。自动切题或手动画出的识别框覆盖在资料图片上：选中框为绿色边框和浅绿色底色，左上角显示绿色圆形勾选按钮；未选中框为灰色边框和浅色底色；未识别框右上角显示黄色「待识别」状态标签和红色删除按钮；点击「开始识别」后，本次参与识别的框继续留在资料页上，状态标签变为蓝色「识别中」；识别完成后，原框继续留在资料页上，状态标签变为绿色「已识别」，并默认恢复为未选中状态。每个框内左上角显示题号标签：系统在进行自动切题时，就需要进行识别，需要根据框选区域的真实题号显示「第X题」，若未获得真实题号，则显示「未识别到题号」，且用提示色与真实题号区分。每个可操作框四角显示绿色调整手柄；用户正在拖拽画框时，页面上显示绿色虚线临时框。',
        fields: [
          '资料页图片',
          '题目文件标签',
          '答案文件标签',
          '本页框数提示',
          '绿色选中框',
          '灰色未选中框',
          '勾选按钮',
          '待识别标签',
          '识别中标签',
          '已识别标签',
          '题号标签',
          '未识别到题号提示',
          '删除按钮',
          '题干/答案/完整类型标签',
          '四角调整手柄',
        ],
        states: [
          '首次进入步骤3：资料处理完成后自动切题，检测出的框直接显示在对应资料页上并默认选中',
          '题目+答案（不同文件）模式：默认只对题目文件自动切题，答案文件不默认自动切题',
          '答案文件手动画框：用户可在答案文件上手动画答案/解析框，未手动画时由全局答案匹配承接',
          '自动切题中：资料区显示切题加载中，切题完成后再展示框',
          '未检测到内容区域：不显示自动框，用户仍可在资料上手动画框',
          '继续上传后：继续上传的文件，若不区分文件类型，则直接加载到原有文件的后面，若区分文件类型，则根据新上传的文件的类型，加载到原有的同类文件的后面；新文件切出的框默认选中',
          '待识别：框正常显示并可选中、移动、缩放或删除，状态标签显示「待识别」',
          '识别中：点击「开始识别」后，本次参与识别的框不消失，状态标签显示「识别中」，框体显示为不可操作样式',
          '已识别：右侧已有识别结果后，原框继续显示，状态标签显示「已识别」，默认未选中，用户可重新选中后再次识别；若用户未对原框进行任何移动或调整框的大小的改动，当用户重新选中后，已识别标签还是已识别；若用户对原框进行了移动或调整了框的大小，则已识别标签变更为「待识别」',
          '题号已识别：框内题号标签显示「第X题」，题号来自识别结果或用户后续编辑后的题号',
          '题号未识别：系统没有获得真实题号时，框内显示「未识别到题号」，不得按画框顺序或页面顺序推测题号',
          '识别完成后返回步骤3：已框选区域和右侧题目数据保留，所有框取消选中，用户可重新选择、调整或再次识别',
        ],
      },
      operation: {
        title: '资料选框操作',
        description: '1、用户在资料空白处按住鼠标并拖动，可手动画出识别框，松开后新框默认选中。\n2、用户可点击左上角圆形勾选按钮切换单个框是否参与识别。\n3、用户可拖动框内部移动位置，拖动四角手柄调整大小；跨页资料支持从当前页拖到下一页形成跨页框。\n4、题目+答案（不同文件）模式下，系统默认只对题目文件自动切题；答案文件不默认生成识别框，用户可在答案文件上手动画答案/解析框。\n5、用户可点击红色删除按钮删除单个框，也可用右侧「清空」悬浮入口删除全部框。\n6、点击「开始识别」时，只有当前选中的框进入识别；进入识别的框在等待右侧结果期间继续显示在左侧资料上，但不可勾选、拖动、缩放或删除，也不能再新画框。\n7、识别完成后，进入识别的框继续留在左侧资料上，系统取消这些框的选中状态；用户可重新选中、移动或调整框后再次点击「开始识别」，按新范围覆盖或更新识别结果。\n8、框内题号只使用系统已获得的真实题号；未获得真实题号时显示「未识别到题号」，不得根据框创建顺序、页面顺序或视觉位置推测题号。\n9、用户未在答案文件上手动画答案/解析框时，系统继续通过全局答案匹配从答案文件中提取并关联答案。',
        permission: '无额外权限限制',
        dataFlow: '识别框来自腾讯云自动切题结果或用户手动画框。框的位置、大小、所在页、文件角色，会持续留在本次识别流程中；继续上传后，继续上传的文件，若不区分文件类型，则直接加载到原有文件的后面，若区分文件类型，则根据新上传的文件的类型，加载到原有的同类文件的后面；开始识别时，系统只读取已选中的框并裁剪对应资料区域，识别完成后把题目数据展示到右侧核对区，同时把真实题号回写到对应框并取消已识别框的选中状态。用户从步骤4返回步骤3时，框选区域、真实题号和已识别题目继续保留，只清空选中状态，便于重新选择或调整后再次识别。',
        exceptions: '自动切题失败或未切出内容时，页面保留手动画框能力；题目+答案（不同文件）模式下，答案文件没有手动画框不阻塞开始识别，由全局答案匹配承接；用户取消识别时，已框选区域不被清空，本次识别中的框退出锁定状态并恢复可操作；识别失败时保留原框和原有题号信息，右侧显示失败信息；系统未识别到题号时，框内持续显示「未识别到题号」，直到后续识别或用户编辑题号后获得真实题号。',
      },
      acceptance: [
        '资料页上能看到自动切题或手动画出的识别框',
        '题目+答案（不同文件）模式下应显示题目文件和答案文件标签',
        '题目+答案（不同文件）模式下默认只对题目文件自动切题',
        '用户可在答案文件上手动画答案/解析框',
        '未手动画答案/解析框时应继续走全局答案匹配',
        '选中框和未选中框样式有明确区分',
        '单框勾选、删除、移动、缩放可用',
        '首次进入步骤3自动框默认选中',
        '继续上传后仅新增框默认选中，原有框状态保留',
        '点击开始识别后，参与识别的框不消失，显示「识别中」并不可勾选、拖动、缩放或删除',
        '识别完成后，原框继续显示为「已识别」且默认未选中',
        '已识别框可重新选中、调整并再次识别',
        '框内存在真实题号时显示「第X题」',
        '系统没有获得真实题号时显示「未识别到题号」',
        '题号不得按画框顺序、页面顺序或视觉位置推测',
        '从步骤4返回步骤3后框保留但全部不选中',
      ],
      source: {
        decisionFile,
        decisionObject: '代码补充：资料预览区选框层 / 逻辑：跨文件模式下答案文件是否参与步骤3框选 / 识别中与已识别框状态 / 题号显示规则',
        relatedFiles: [...relatedFiles, 'src/types/recognition.ts'],
      },
    },
    {
      id: 'BOX_STEP-011',
      title: '增量识别进度条（已有题目时再次点击开始识别）',
      sourceType: 'decision',
      objectType: 'region',
      objectName: '增量识别进度条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-incremental-progress',
      anchorStatus: 'implemented',
      activate: activateRecognizeQuestions('box-step-incremental-progress'),
      display: {
        title: '增量识别进度条',
        description: '当用户已有一部分识别完成的题目，并在第 4 步「核对识别结果」继续框选新区域或重新框选已有题干后，右侧面板不再清空为全屏加载动画，而是在模式切换按钮下方显示一条细进度条。进度条高度约36px，包含加载动画、进度文案和暂停/取消按钮。进度条上的提示文案按场景分类展示：\n场景A（仅新增框选）：「正在识别 X 个新增区域...」\n场景B（仅重新框选已识别题目）：「正在重新识别 X 道题目...」\n场景C（混合新增+重新框选）：「正在识别 X 个区域（含 Y 道重新识别）...」\n已有的题目卡片在进度条下方保持可见可滚动；被重新识别的题目卡片显示「识别中」遮罩，其他题目卡片保持正常。识别完成后进度条自动消失，新增或更新的题目卡片高亮闪烁。',
        fields: ['进度条', '加载动画', '场景化进度文案', '暂停按钮', '取消按钮', '已有题目卡片'],
        states: [
          '场景A（仅新增框选）：进度文案「正在识别 X 个新增区域...」，已有题目卡片全部正常显示可滚动',
          '场景B（仅重新框选已识别题目）：进度文案「正在重新识别 X 道题目...」，被重新识别的题目卡片变为半透明+不可操作，中央覆盖「识别中...」标签，其余题目正常显示',
          '场景C（混合新增+重新框选）：进度文案「正在识别 X 个区域（含 Y 道重新识别）...」，被重新识别的题目卡片半透明+「识别中...」遮罩，其余题目正常显示，新增题目识别完成后按题号插入列表',
          '首次识别（无已有题目）：保持原有的全屏加载动画不变',
        ],
      },
      operation: {
        title: '增量识别流程',
        description: '1、系统自动检测本次选中的框哪些是已识别过的，哪些是新增的。\n2、用户在第 4 步补画漏掉的题目区域时，本次结果作为新增题目处理；新增题目不会直接排在列表末尾，而是按识别到的题号插入到已有题目之间。\n3、用户在第 4 步重新框选已有题目的完整题干时，本次结果作为重新识别处理；对应题目卡片在识别期间变为半透明，中央覆盖「识别中...」标签，不可操作。\n4、不受本次识别影响的题目卡片保持正常显示，用户可滚动查看、切换图片/编辑模式。\n5、识别期间不允许编辑任何题目内容。\n6、暂停后所有状态保持，已识别题目卡片继续可见。\n7、取消识别后，被重新识别的题目恢复回识别前的旧内容，新增的框选不产生新题目，进度条消失。\n8、识别完成后：重新识别的题目卡片恢复不透明并替换为新内容，蓝色边框+脉冲动画闪烁2.5秒；新增题目按题号插入列表，绿色边框+脉冲动画闪烁2.5秒。',
        permission: '无额外权限限制',
        dataFlow: '识别结果通过SSE流式返回。新增题目按题号插入已有题目列表；同题号重新识别结果沿用原题目位置并替换原题目的题干、答案和解析；无法获得有效题号的新增结果保留在当前列表末尾等待用户核对。',
        exceptions: '首次识别（无已有题目）时保持原有全屏加载动画；进度条文案根据三种场景自动区分；暂停/取消不丢失已有题目数据',
      },
      acceptance: [
        '三种场景的进度文案正确显示',
        '场景B重识别卡片正确置灰+遮罩',
        '场景C混合场景两者都正确',
        '识别完成动画：新题目绿色闪烁，重识别题目蓝色闪烁',
        '暂停/取消后已有题目数据不丢失',
        '识别期间已有题目可滚动但不可编辑',
        '新增题目按题号插入已有题目之间',
        '重复题目重新识别后原位置覆盖，不新增重复卡片',
      ],
      source: {
        decisionFile,
        decisionObject: '增量识别：已有题目时再次识别的交互优化',
        relatedFiles,
      },
    },
    {
      id: 'BOX_STEP-013',
      title: '更多工具面板展开与收起规则',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'panel',
      objectName: '更多工具面板',
      module: moduleName,
      pageName,
      route,
      anchorId: 'box-step-more-tools',
      anchorStatus: 'implemented',
      activate: activateMoreTools('box-step-more-tools'),
      display: {
        title: '更多工具面板',
        description: '步骤3「选择识别内容」中，资料预览区右下角显示「更多工具」悬浮入口。入口默认收起，只显示圆形加号按钮和「更多工具」文字。用户展开后，面板显示「修改资料」和「补充资料」两个操作项。',
        fields: ['更多工具', '修改资料', '补充资料'],
        states: [
          '默认收起：只显示更多工具入口',
          '展开状态：显示修改资料和补充资料',
          '流程切换后：默认回到收起状态',
          '确认弹窗打开时：面板收起',
          '30秒无操作：面板自动收起',
        ],
      },
      operation: {
        title: '展开与自动收起',
        description: '1、用户点击「更多工具」入口后，展开或收起更多工具面板。\n2、面板展开后，用户可以点击「修改资料」返回上传资料步骤，或点击「补充资料」补充本地文件。\n3、流程切换或打开任意确认弹窗时，系统强制收起「更多工具」面板。\n4、用户回到步骤3时，更多工具默认关闭，需要手动重新展开。\n5、面板打开后若30秒无操作，系统自动收起面板。',
        permission: '无额外权限限制',
        dataFlow: '面板展开状态只影响当前页面操作入口展示，不改变资料、框选或识别结果数据。',
        exceptions: '用户在更多工具面板展开后触发步骤切换、确认弹窗或长时间无操作时，面板应及时收起，避免返回步骤3后保留过期展开状态。',
      },
      acceptance: [
        '默认只显示更多工具入口',
        '点击更多工具后可展开和收起面板',
        '展开后显示修改资料和补充资料',
        '流程切换时更多工具面板应收起',
        '打开任意确认弹窗时更多工具面板应收起',
        '回到步骤3时更多工具默认关闭',
        '展开后30秒无操作应自动收起',
      ],
      source: {
        decisionFile,
        decisionObject: '交互：更多工具面板缺少关闭方式 / 交互：更多工具展开状态在流程切换后的恢复规则',
        relatedFiles,
      },
    },
  ],
  excludedDecisions: [
    {
      objectName: '信息提示栏（box-step-info-bar）空壳',
      reason: '已确认直接删除空信息栏，把纵向空间还给资料预览区，不作为需求卡片展示。',
      sourceDecision: '第三轮审核 17：区域：信息提示栏（box-step-info-bar）空壳',
    },
    {
      objectName: '手动关联答案悬浮球入口与进入提示',
      reason: '手动关联答案属于步骤4「核对识别结果」内的子状态，不纳入步骤3「选择识别内容」需求卡片。',
      sourceDecision: '第三轮审核 18、22：手动关联答案仅在步骤4显示，并在进入时显示 toast',
    },
    {
      objectName: '修改识别方式 hover 触发',
      reason: '该入口属于选择识别方式返回修改规则，已由选择识别方式注册表覆盖，本页不重复生成需求卡片。',
      sourceDecision: '第三轮审核 20：修改识别方式 hover 交互保持现状',
    },
    {
      objectName: '帮助弹窗步骤3说明内容',
      reason: '已确认保持现状，本轮不新增页面级角标或悬浮说明。',
      sourceDecision: '第三轮审核 23：帮助弹窗内容不变',
    },
  ],
};
