import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
  'src/app/api/recognize-questions/route.ts',
  'src/lib/ai-recognizer.ts',
  'src/app/paper-edit/page.tsx',
];
const decisionFile = 'docs/prd-workflow/decisions/question-answer-review-step.decision.md';

const pageName = '核对识别结果';
const route = '/homework → 识别作业资料 → 核对识别结果';
const moduleName = '识别作业资料';

function activateReview(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到核对识别结果步骤', step: 'review' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

export const questionAnswerReviewStepRegistry: RequirementRegistry = {
  registryId: 'question-answer-review-step',
  pageName,
  route,
  module: moduleName,
  description: '记录步骤 4「核对识别结果」的完整页面逻辑，覆盖匹配状态提示、题目卡片展示、题目卡片排序与删除、子题结构与编辑、答案/解析核对与关联、题型切换保护、图片模式与编辑模式切换、加入试卷等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'REVIEW_STEP-001',
      title: '匹配状态提示（分步模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '匹配状态提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-match-banner',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-match-banner'),
      display: {
        title: '匹配状态提示',
        description: '题目+答案模式下，右侧面板顶部显示匹配状态提示条。存在待匹配题目时：「识别结果：共 X 道题目，已匹配答案 Y 题，待匹配答案 N 题（待匹配答案的题目，可在左侧框选答案/解析手动关联题目）」。全部匹配后：「全部题目已匹配答案和解析，可将题目加入试卷了~」。提示条始终完整展示，不可收起或展开。',
        fields: ['父题数量', '已匹配答案数量', '待匹配答案数量'],
        states: ['存在待匹配题目', '全部匹配'],
      },
      operation: {
        title: '查看匹配进度',
        description: '提示条不可点击、不可收起、不可展开。存在待匹配题目时，用户可通过左侧框选答案/解析手动关联。',
        permission: '无额外权限限制',
        dataFlow: '匹配统计根据已识别的题目、答案和解析数据计算。',
        exceptions: '没有识别结果时不展示。',
      },
      acceptance: [
        '存在待匹配题目时，提示条正确显示识别结果统计',
        '待匹配数量正确',
        '全部题目均已匹配答案/解析时，提示条显示「全部题目已匹配答案和解析，可将题目加入试卷了~」',
      ],
      source: { decisionFile, decisionObject: '答案匹配状态与统计', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-002',
      title: '题目卡片展示（仅识别题目模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '题目卡片（仅识别题目模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-single',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-single'),
      display: {
        title: '仅识别题目模式下的题目卡片',
        description: '仅识别题目模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准；补识别新增题按题号插入已有题目之间；重识别同题号题干时原位置覆盖。每张卡片含题号、题型、题目内容和图片预览，不展示答案/解析区域。',
        fields: ['题号', '题型', '题目内容', '图片预览'],
        states: ['图片模式：显示截图', '编辑模式：显示识别文字', '新增题：按题号插入', '重识别题：原位置覆盖'],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n8、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片正确展示',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '图片/编辑模式可切换',
        '题型和内容可编辑',
        '裁剪功能可用',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
      ],
      source: { decisionFile, decisionObject: '仅识别题目模式展示', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-003',
      title: '题目卡片展示（识别题目和答案模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '题目卡片（识别题目和答案模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片',
        description: '题目+答案模式下，右侧按题号展示每道题目。题号顺序以左侧资料页为准。每张卡片含题号、题型、题目内容、答案区域和解析区域。匹配状态用四种标签区分：「答案解析已匹配」「未匹配到答案」「未匹配到解析」「未匹配到答案和解析」。填空题按空位展示答案，解答题按子题结构展示子题答案和解析。补识别新增题按题号插入，重识别同题号题干时原位置覆盖。',
        fields: ['题号', '题型', '题目内容', '答案', '解析', '匹配状态标签', '子题答案/解析'],
        states: [
          '答案和解析均匹配：显示「答案解析已匹配」',
          '未匹配到答案：显示「未匹配到答案」',
          '未匹配到解析：显示「未匹配到解析」',
          '未匹配到答案和解析：显示「未匹配到答案和解析」',
          '四种标签样式有区分',
          '图片模式：显示截图',
          '编辑模式：显示识别文字',
          '新增题：按题号插入',
          '重识别题：原位置覆盖',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、可切换图片模式查看截图或编辑模式修改文字。\n2、两种模式下均可修改题型、编辑答案和解析。\n3、点击左侧题号框可定位到右侧对应题目，点击右侧题号可定位到左侧对应资料位置。\n4、编辑模式下可修改题目内容。\n5、可使用裁剪功能截取题目图片。\n6、可为复合题添加子题。\n7、未匹配答案时，可通过再次框选并点击开始识别更新结果；也可点击【答案】【解析】后的关联图标进入关联态，跨文件模式下自动定位到答案文件位置，无法定位到具体位置则定位到答案文件开始位置。\n8、补识别新增题：左侧框选漏掉题干后点击开始识别，新题卡按题号插入。\n9、重识别已有题：重新框选完整题干后点击开始识别，原题卡覆盖更新。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于 AI 识别和答案匹配结果。新增题按题号插入，重识别同题号覆盖原题卡。用户编辑后更新本地状态，加入试卷时传递给下游。',
        exceptions: '识别失败时停留在框选阶段。',
      },
      acceptance: [
        '题目卡片含答案和解析区域',
        '右侧题号顺序应以左侧资料页题号顺序为准',
        '四种答案/解析匹配状态标签正确显示且样式有区分',
        '点击左侧题号框时右侧自动定位到对应题目',
        '单击右侧题号时左侧自动定位到对应资料位置',
        '未匹配答案时可通过再次框选并开始识别更新结果',
        '答案/解析关联图标可引导用户定位答案文件并进入关联状态',
        '填空题按空位显示答案',
        '解答题显示子题结构',
        '图片/编辑模式可切换',
        '第4步补识别新增题后应按题号插入列表',
        '第4步重识别重复题后应原位置覆盖',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式展示', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-004',
      title: '子题结构与编辑',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '子题结构区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-subquestion',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-subquestion'),
      display: {
        title: '子题结构',
        description: '复合题型（解答题、完形填空、阅读理解等）支持子题结构。识别时系统自动拆分大题的子题，右侧展示时已添加好子题，每个子题含序号（①②③...）、自动匹配的题型、答案和解析区域。父题无需显示子题匹配进度标签。乐课网资源库中无子题的大题不显示【+子题】按钮。\n【6.16】填空题（含父题和子题）题干下方显示「+插入空位」按钮和空位数量匹配状态文案（题干空位与答案空位一致/题干少/题干多三种状态）。点击「插入空位」后在题干光标位置插入下划线，答案区自动增加对应空位输入框。',
        fields: ['子题序号', '子题题型', '子题答案', '子题解析', '+子题按钮', '删除子题按钮', '【6.16】+插入空位按钮', '【6.16】空位匹配状态文案'],
        states: [
          '资源库无子题的大题：不显示【+子题】',
          '新增子题：空子题',
          '【6.16】空位匹配状态：一致（灰色正常文案）、题干空位少（橙色警告）、答案空位少（蓝色提示），文案仅在编辑模式下显示',
          '【6.16】图片模式下插入空位：不修改图片内容，仅在答案区末尾新增一个答案输入框',
          '【6.16】删除空位/下划线：两侧独立操作不联动',
          '删除子题确认弹窗',
          '【6.16】填空题多空位：答案区按空位逐个显示输入框，每个空位独立填写',
          '【6.16】子题删除：顶部标记条和底部答案/解析区各有一个删除入口',
          '【6.16】子题编号：使用带圈数字①②③...⑩，超过10个回退普通数字',
        ],
      },
      operation: {
        title: '子题编辑',
        description: '1、题干子题标记≥2时系统自动生成子题结构。\n2、子题题型根据题干要求自动匹配，不固定继承父题。\n3、子题题型可选项根据菁优网的题型显示。\n4、答案/解析按子题标记自动拆分；无法拆分时保留在父题区。\n5、资源库无子题的大题不显示【+子题】。\n6、点击「+子题」新增空子题。\n7、删除有内容的子题时弹窗确认：「该子题已有答案/解析，删除后内容将一并移除，是否继续？」\n【6.16】8、AI优先策略：AI返回子题结构时优先使用，AI未返回时才用前端文本正则匹配兜底拆分。\n【6.16】9、填空题子题自动检测题干中下划线数量为空白数量，无论是在编辑模式还是图片模式下，用户都可通过【+插入空位】按钮手动调整答案/解析的空位数，答案区按空位逐个显示输入框。在编辑模式下，用户光标定位在题干位置点击插入空位后，题干中会同步增加下划线。\n【6.16】10、子题使用带圈数字①②③...编号，上限10个，超过回退普通数字。\n【6.16】11、答案按子题标记自动拆分；AI 直接返回的子题答案/解析优先于前端文本拆分结果。\n【6.16】12、填空题多空位答案支持分号、逗号、顿号、序号、空格、斜杠、竖线等多种分隔格式自动拆分。\n【6.16】13、删除答案区空位不自动删除题干下划线，删除题干下划线也不自动删除答案区空位；页面常驻显示空位与下划线数量匹配状态文案。\n【6.16】14、图片模式下点击「插入空位」，不修改图片内容，仅在答案区已有空位末尾新增一个答案输入框。\n【6.16】15、题干下划线数量与答案空位数匹配状态文案仅在编辑模式下显示。\n【6.16】16、最多支持插入 20 个空位；已达到 20 个时点击「插入空位」提示——"最多支持插入 20 个空位"。\n【6.16】17、父题和子题各自独立管理空位，互不影响。',
        permission: '无额外权限限制',
        dataFlow: '子题数据作为题目数据的一部分，加入试卷时保留完整子题结构。',
        exceptions: '题干少于2个子题标记时不自动生成子题结构。',
      },
      acceptance: [
        '子题自动拆分正确',
        '子题题型自动匹配',
        '资源库无子题的大题不显示【+子题】按钮',
        '新增子题为空',
        '删除有内容的子题弹窗确认',
        '加入试卷保留子题结构',
      ],
      source: { decisionFile, decisionObject: '子题结构与编辑', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-005',
      title: '答案关联icon',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '答案/解析关联图标',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-link-icon',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-answer-link-icon'),
      display: {
        title: '答案关联icon',
        description: '每道题的「答案」「解析」标题后方显示轻量关联图标。跨文件模式下点击后左侧资料页自动定位到答案文件。关联中图标高亮。\n【6.16】用户点击关联图标后可在左侧资料区框选该题对应的答案或解析区域，框选范围允许同时包含答案和解析；提交后系统调用AI对框内内容进行识别，自动判断内容为答案、解析或两者兼有，并将识别结果分别回显到该题对应的答案和解析字段。',
        fields: ['答案字段关联图标', '解析字段关联图标'],
        states: [
          '默认态：标题后方显示关联图标',
          '关联中：图标高亮',
          '跨文件模式：点击后自动定位到答案文件',
        ],
      },
      operation: {
        title: '手动关联答案',
        description: '1、点击「答案」或「解析」后的关联图标，直接进入关联态。\n2、跨文件模式下自动定位到答案文件位置；无法定位到具体位置则定位到答案文件开始位置。\n3、用户在左侧框选内容后，识别结果自动填入对应答案/解析区域。\n4、框选时间时包含答案和解析，系统自动拆分并分别回显。\n【6.16】5、关联完成后自动退出关联态，用户需重新点击下一道题的关联图标进入。\n【6.16】6、再次点击同一个关联图标可切换退出关联态（图标恢复为未点亮状态）。',
        permission: '无额外权限限制',
        dataFlow: '框选内容识别结果写入对应题目的答案/解析区域，加入试卷时随题目数据传递。',
        exceptions: '跨文件模式无法定位到具体位置时，定位到答案文件开始位置。',
      },
      acceptance: [
        '答案和解析标题后方显示关联图标',
        '点击关联图标后直接进入关联答案状态',
        '跨文件模式点击关联图标后定位到答案文件',
        '框选内容识别后可自动拆分并回显到答案和解析区域',
      ],
      source: { decisionFile, decisionObject: '答案关联icon', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-006',
      title: '图片模式与编辑模式切换',
      sourceType: 'code',
      objectType: 'tab',
      objectName: '图片模式/编辑模式切换按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-view-mode',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-view-mode'),
      display: {
        title: '视图模式切换',
        description: '右侧面板顶部有「图片模式」和「编辑模式」两个切换按钮。图片模式显示题目截图，编辑模式显示识别文字并可编辑。编辑模式下显示提示「请注意甄别AI识别内容」。切换时有加载动画。编辑模式有改动时切回图片模式，显示确认弹窗「确认切回图片模式吗？」，说明「切回图片模式，您在编辑模式下调整过的内容将不会保存」。',
        fields: ['图片模式按钮', '编辑模式按钮', '请注意甄别AI识别内容', '确认切回图片模式弹窗'],
        states: [
          '图片模式选中：绿色高亮',
          '编辑模式选中：绿色高亮',
          '切换中：加载动画',
          '编辑模式有改动后切回图片模式：显示确认弹窗',
        ],
      },
      operation: {
        title: '切换视图模式',
        description: '1、点击「图片模式」查看题目原始截图。\n2、点击「编辑模式」编辑识别文字、答案和解析。\n3、编辑模式无内容改动时可直接切回图片模式，有改动时需弹窗确认。确认弹窗：「确认切回图片模式吗？」「切回图片模式，您在编辑模式下调整过的内容将不会保存」。\n4、点击取消停留在编辑模式，点击确认切换到图片模式，后续再进入编辑模式显示新识别后的内容。\n5、图片模式下的裁剪结果在切回图片模式时保留。\n6、用户点击步骤3确认弹窗时，清空编辑的图片和文字数据。',
        permission: '无额外权限限制',
        dataFlow: '图片裁剪数据和编辑改动作为临时编辑结果。确认切回图片模式后不保存编辑改动，后续进入编辑模式时展示新识别内容。',
        exceptions: '编辑模式有改动时切回图片模式必须先弹窗确认，取消不丢弃编辑内容，确认才切换并放弃改动。',
      },
      acceptance: [
        '两种模式可切换',
        '切换有加载动画',
        '编辑模式可编辑内容',
        '图片模式显示截图',
        '编辑模式无改动时可直接切回图片模式',
        '编辑模式有改动时切回图片模式应显示确认弹窗',
        '点击取消后停留在编辑模式',
        '点击确认后切换到图片模式且不保存本次编辑模式改动',
        '点击步骤条步骤3的确认弹窗后清空用户编辑的图片和文字数据',
      ],
      source: { decisionFile, decisionObject: '图片模式/编辑模式', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-007',
      title: '题目图片裁剪功能',
      sourceType: 'code',
      objectType: 'button',
      objectName: '裁剪按钮与裁剪操作',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-crop',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-crop'),
      display: {
        title: '题目图片裁剪',
        description: '编辑模式下提供「使用图片」开关，图片模式下提供裁剪按钮。裁剪模式下图片四周显示调整手柄，底部展示「取消」和「确认裁剪」按钮。已裁剪后可「还原」到用户在左侧框选的原始图片。',
        fields: ['使用图片开关', '裁剪按钮', '确认裁剪按钮', '取消按钮', '还原按钮'],
        states: [
          '未开启使用图片：显示识别文字',
          '裁剪模式：显示调整手柄和操作按钮',
          '已裁剪：可还原到左侧框选的原始图片',
        ],
      },
      operation: {
        title: '裁剪题目图片',
        description: '1、编辑模式下开启「使用图片」显示题目图片。\n2、点击裁剪按钮进入裁剪模式，拖动手柄调整范围。\n3、确认裁剪保存结果，取消退出裁剪模式。\n4、裁剪后可点击「还原」恢复到原始图片。',
        permission: '无额外权限限制',
        dataFlow: '裁剪结果保存到当前题目，加入试卷时随题目数据传递。',
        exceptions: '无异常场景',
      },
      acceptance: [
        '编辑模式下有使用图片开关',
        '图片模式下有裁剪按钮',
        '确认裁剪保存结果',
        '取消不保存',
        '可还原到用户在左侧框选的图片',
      ],
      source: { decisionFile, decisionObject: '裁剪功能', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-008',
      title: '加入试卷按钮',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '加入试卷按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-add-to-paper-btn',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-add-to-paper-btn'),
      display: {
        title: '加入试卷按钮',
        description: '顶部步骤条右侧操作区，文案「加入试卷」。有题目时绿色可点击，无题目时置灰。【6.16】题目+答案模式下、编辑模式下，加入试卷前额外校验填空题答案空位与题干下划线是否匹配。',
        fields: ['加入试卷'],
        states: ['可用态：有题目（绿色可点击）', '禁用态：无题目（灰色）', '【6.16】校验态：编辑模式下校验空位不匹配并弹窗提示'],
      },
      operation: {
        title: '加入试卷',
        description: '1、点击后检查是否有未匹配答案或解析。\n2、有缺失时弹窗：「确认加入试卷吗？」「当前还有 X 道题的答案/解析没有补充，您可以在后续组卷页面使用AI批量补充功能，进行补充。」（一道大题存在答案或解析未匹配即计1道）。取消停留在步骤4，确认进入后续组卷页面。\n3、确认后完整保留父题、子题、子题答案/解析、填空空位答案、题型、选项数和题目图片传递给下游。\n4、加入试卷前保存当前状态，供从试卷编辑页返回时恢复。\n5、题目数据保存失败时停留在步骤4并提示：「加入试卷失败，题目数据暂未保存，请重试」。\n【6.16】6、题目+答案模式下、编辑模式下，加入试卷时额外校验填空题答案空位与题干下划线是否匹配；不匹配时在确认弹窗中合并展示：「另有 X 道填空题的答案空位与题干空位不匹配」。\n【6.16】7、空位不匹配按父题和子题独立统计，合并为"X 道填空题的空位不匹配"。\n【6.16】8、取消后，同时存在答案缺失和空位不匹配时，各取第一个，优先定位到更靠近列表顶部的那一个。',
        permission: '无额外权限限制',
        dataFlow: '题目数据传递给试卷编辑页面，弹窗状态暂存供返回恢复。',
        exceptions: '有未匹配答案/解析时需弹窗二次确认。题目数据保存失败时阻断加入并提示。',
      },
      acceptance: [
        '有题目时按钮可用',
        '无题目时按钮置灰',
        '有答案或解析缺口时显示「确认加入试卷吗？」弹窗',
        '点击取消后停留在步骤4',
        '点击确认后进入后续组卷页面',
        '加入后数据完整传递',
        '题目数据保存失败时停留在核查页并显示失败提示',
      ],
      source: { decisionFile, decisionObject: '加入试卷', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-009',
      title: '识别失败降级处理',
      sourceType: 'code+decision',
      objectType: 'state',
      objectName: '识别失败降级状态',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-error-fallback',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-error-fallback'),
      display: {
        title: '识别失败处理',
        description: '生产环境识别失败时停留在框选阶段，不进入核对页面。显示「识别失败，请调整框选范围后重试」。',
        fields: ['识别失败提示'],
        states: ['识别失败：停留在框选阶段'],
      },
      operation: {
        title: '识别失败处理',
        description: '1、AI 识别失败时不生成模拟数据，不进入核查页面。\n2、用户可调整框选范围后重新识别。\n3、仅识别题目模式下框选区域包含答案/解析时，由用户在核查页面通过裁剪手动处理。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '识别失败时需用户手动重试。',
      },
      acceptance: [
        '识别失败停留在框选阶段',
        '显示错误提示',
        '不生成模拟数据',
        '可重试',
      ],
      source: { decisionFile, decisionObject: '识别失败降级', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-012',
      title: '核对识别结果步骤条回退确认',
      sourceType: 'code',
      objectType: 'step',
      objectName: '步骤条回退确认',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-single-mode-back',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-single-mode-back'),
      display: {
        title: '步骤条回退',
        description: '步骤4中，第1步「上传资料」、第2步「选择识别方式」、第3步「选择识别内容」为可点击回退节点，第4步为当前激活态（绿色高亮）。点击前三步时分别弹出对应确认弹窗。',
        fields: ['步骤条第1步', '步骤条第2步', '步骤条第3步', '步骤条第4步'],
        states: [
          '第1步：可点击，弹出确认更换资料弹窗',
          '第2步：可点击，弹出确认更换识别方式弹窗',
          '第3步：可点击，弹出确认重新选择识别内容弹窗',
          '第4步：绿色高亮当前激活态',
        ],
      },
      operation: {
        title: '回退到前面步骤',
        description: '1、点击「上传资料」→ 弹窗「确认更换资料吗？」「更换资料将清空当前的识别结果。」\n2、点击「选择识别方式」→ 弹窗「确认更换识别方式吗？」「更换识别方式将清空当前的识别结果。」\n3、点击「选择识别内容」→ 弹窗「确认重新选择识别内容吗？」「重新选择识别内容将清空当前识别结果，并恢复进入步骤4之前框选的题目框。」\n4、三个弹窗均为：取消留在步骤4，确认返回对应步骤。',
        permission: '无额外权限限制',
        dataFlow: '确认后按对应回退动作清空识别结果，取消则不清空。回退到步骤3时，回显进入步骤4之前的框选状态，而非进入步骤3时的初始框。',
        exceptions: '未确认前不得离开步骤4。',
      },
      acceptance: [
        '点击步骤1应显示确认更换资料弹窗',
        '点击步骤2应显示确认更换识别方式弹窗',
        '点击步骤3应显示确认重新选择识别内容弹窗',
        '三个弹窗点击取消后均停留在步骤4',
        '三个弹窗点击确认后均返回对应步骤条位置',
      ],
      source: { decisionFile, decisionObject: '步骤条回退确认', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-013',
      title: '题目卡片排序功能移除',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片排序功能',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder'),
      display: {
        title: '题目卡片排序能力移除',
        description: '本期移除题目卡片拖动排序功能。题目顺序按识别结果和左侧资料题号顺序展示，上移和下移操作保留。',
        fields: ['拖动题目顺序功能', '上移题目按钮', '下移题目按钮'],
        states: [
          '本期移除：不展示拖动排序入口，保留上移下移',
          '题目顺序：按识别结果和左侧资料题号顺序展示',
        ],
      },
      operation: {
        title: '题目顺序调整',
        description: '1、本期不支持拖动调整题目顺序。仅支持上移或下移调整题目顺序。\n2、加入试卷时按当前核对列表顺序传递。',
        permission: '无额外权限限制',
        dataFlow: '题目顺序不产生额外数据，加入试卷时按当前列表顺序传递。',
        exceptions: '顺序不符合预期时需返回选择识别内容重新框选或重新识别。',
      },
      acceptance: [
        '题目卡片不展示拖动排序入口',
        '题目卡片保留上移和下移按钮',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前核对列表顺序传递题目',
      ],
      source: { decisionFile, decisionObject: '题目卡片排序操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-014',
      title: '删除题目卡片',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete'),
      display: {
        title: '题目卡片删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-015',
      title: '题目卡片排序（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片上移/下移按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片排序',
        description: '题目+答案模式下，题目卡片提供上移、下移操作图标，不提供拖动排序。首题上移置灰，末题下移置灰。',
        fields: ['上移题目按钮', '下移题目按钮'],
        states: [
          '第一张题目：上移置灰',
          '最后一张题目：下移置灰',
          '中间题目：上移和下移均可',
        ],
      },
      operation: {
        title: '调整题目顺序',
        description: '1、仅通过上移、下移调整题目顺序，不支持拖拽。\n2、加入试卷时按当前右侧最终顺序传递。',
        permission: '无额外权限限制',
        dataFlow: '排序结果保存在当前列表中，加入试卷时按最终顺序传递。',
        exceptions: '边界题目不可继续向对应方向移动。',
      },
      acceptance: [
        '题目卡片展示上移和下移操作图标',
        '题目卡片不展示拖动排序入口',
        '用户只能通过上移、下移改变题目顺序',
        '裁剪功能可用时不与题目排序功能冲突',
        '加入试卷按当前右侧最终顺序传递题目、答案和解析',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片排序操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-016',
      title: '删除题目卡片（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete-stepwise'),
      display: {
        title: '题目+答案模式下的删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮，默认为灰色，悬停时红色强调并显示「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['默认态：灰色', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除后题目卡片从列表移除。\n2、被删除题目的全部内容不再加入试卷。',
        permission: '无额外权限限制',
        dataFlow: '删除后题目、答案和解析不再传递给试卷编辑页面。',
        exceptions: '不提供二次确认和撤销入口，误删后需重新识别或补录。',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-017',
      title: '题型切换结构保护',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'dialog',
      objectName: '切换题型确认弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-type-guard',
      anchorStatus: 'planned',
      activate: activateReview('review-step-question-type-guard'),
      display: {
        title: '切换题型确认',
        description: '题目已有子题、扩展选项、多空答案、答案或解析时，切换题型前显示确认弹窗：「确认切换题型吗？」「切换题型将调整题目结构，可能清空子题的答案及解析」。无结构化内容时直接切换。',
        fields: ['题型选择器', '切换题型确认弹窗', '确认按钮', '取消按钮'],
        states: ['无结构化内容：直接切换', '已有结构化内容：弹窗确认', '取消：保持原题型', '确认：按新题型调整结构'],
      },
      operation: {
        title: '切换题型',
        description: '1、选择新题型后，系统判断是否有子题、扩展选项、多空答案、答案或解析。\n2、有以上内容时先弹窗确认，无则直接切换。\n3、取消保持原题型和原内容，确认后切换并按新题型调整结构。',
        permission: '无额外权限限制',
        dataFlow: '切换后的题型和结构化内容随题目数据传递给试卷编辑页面。',
        exceptions: '已有结构化内容时必须先确认，避免误切题型导致子题内容清空。',
      },
      acceptance: [
        '无结构化内容时可直接切换题型',
        '已有子题、扩展选项、多空答案、答案或解析时先显示确认弹窗',
        '取消后题型和内容不变',
        '确认后才按新题型调整结构',
        '确认弹窗文案与决策一致',
      ],
      source: { decisionFile, decisionObject: '切换题型时已有结构化内容的保护规则', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-018',
      title: '答案解析清空操作',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.5',
      objectType: 'button',
      objectName: '答案/解析清空按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-clear',
      anchorStatus: 'planned',
      activate: activateReview('review-step-answer-clear'),
      display: {
        title: '答案解析清空按钮',
        description: '题目卡片和子题区域中有答案、解析或空位答案时，显示对应清空入口（答案区「清空」、解析区「清空」、空位清空图标、子题清空图标）。无内容时隐藏。',
        fields: ['清空答案', '清空解析', '空位答案清空图标', '子题答案清空图标', '子题解析清空图标'],
        states: ['有内容：显示清空入口', '无内容：隐藏清空入口'],
      },
      operation: {
        title: '清空答案解析',
        description: '1、点击清空入口后立即清除对应内容，不弹二次确认。\n2、清空后匹配状态按剩余内容重新计算。',
        permission: '无额外权限限制',
        dataFlow: '清空后的内容保存在当前列表中，加入试卷时按清空后内容传递。',
        exceptions: '不提供撤销入口；误清空需重新输入或重新框选。',
      },
      acceptance: [
        '有内容时显示对应清空入口',
        '无内容时隐藏对应清空入口',
        '点击清空后立即清除对应内容',
        '清空时不弹出二次确认',
        '清空后匹配状态按最新内容更新',
      ],
      source: { decisionFile, decisionObject: '清空答案、解析和空位答案的保护规则', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-019',
      title: '题卡分组与排序规则',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.16',
      objectType: 'region',
      objectName: '题卡分组标题与排序',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-groups',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-groups'),
      display: {
        title: '题卡分组展示',
        description:
          '右侧题卡列表按资料文件和页码分组展示。每组以绿色圆角标签作为分组标题，显示「文件名 | 第N页」，标题两侧有灰色分隔线。分组标题不可点击。',
        fields: ['分组标题', '文件名', '第N页'],
        states: [
          '多文件多页：按文件+页码分为多个分组，每组独立展示标题',
          '单文件单页：仅有一个分组，分组标题始终显示',
        ],
      },
      operation: {
        title: '分组排序规则',
        description:
          '【6.16】1、组内题卡按左侧来源框的空间位置排序：文件→页码→Y坐标→X坐标→题号→原始插入顺序。\n【6.16】2、用户可通过题卡上的上移/下移按钮手动调整题目顺序，可自由跨组移动。\n【6.16】3、加入试卷时按当前列表最终顺序传递，保留用户手动排序结果。\n【6.16】4、分组标题不根据组内匹配状态变色，统一样式。',
        permission: '无额外权限限制',
        dataFlow: '分组根据每道题目的来源框所在文件和页码自动计算，排序通过 useMemo 自动执行，手动排序后更新题目列表。',
        exceptions: '单组时标题不隐藏。',
      },
      acceptance: [
        '分组标题正确显示文件名和页码',
        '组内排序按来源框空间位置排列',
        '上移/下移按钮可用',
        '加入试卷保留手动排序结果',
      ],
      source: { decisionFile, decisionObject: '题卡分组与排序规则', relatedFiles },
    },
  ],
  excludedDecisions: [
    {
      objectName: '解答题答案/解析自动分发规则中的不可拆分情况',
      reason: '已纳入 REVIEW_STEP-004 的异常处理中',
      sourceDecision: '决策 3',
    },
  ],
};
