import type { RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
  'src/app/api/recognize-questions/route.ts',
  'src/lib/ai-recognizer.ts',
  'src/app/paper-edit/page.tsx',
];
const decisionFile = 'docs/prd-workflow/decisions/question-answer-review-step.decision.md';

const pageName = '核查题目信息';
const route = '/homework → 识别作业资料 → 核查题目信息步骤';
const moduleName = '识别作业资料';

function activateReview(anchorId: string) {
  return [
    { type: 'openDialog' as const, label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep' as const, label: '切换到核查题目信息步骤', step: 'manual_link' },
    { type: 'scrollTo' as const, label: '定位页面对象', anchorId },
    { type: 'highlight' as const, label: '高亮页面对象', anchorId },
  ];
}

export const questionAnswerReviewStepRegistry: RequirementRegistry = {
  registryId: 'question-answer-review-step',
  pageName,
  route,
  module: moduleName,
  description: '记录核查题目信息步骤的完整页面逻辑，覆盖匹配状态提示、题目卡片展示、题目卡片排序与删除、子题结构与编辑、答案/解析核对与关联、图片模式与编辑模式切换、加入试卷等交互边界。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'REVIEW_STEP-001',
      title: '匹配状态提示（分步模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '匹配状态提示条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-match-banner',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-match-banner'),
      display: {
        title: '匹配状态提示',
        description: '识别题目和答案模式下，右侧面板顶部显示匹配状态提示条：「请检查题目与答案匹配情况：共 X 道题目，已匹配答案 Y 题，待匹配答案 N 题（待匹配答案的题目，可在左侧框选答案/解析手动关联题目）」。提示条始终完整展示，不可收起或展开。',
        fields: ['父题数量', '已匹配答案数量', '待匹配答案数量'],
        states: ['正常展示', '全部匹配：无需显示'],
      },
      operation: {
        title: '查看匹配进度',
        description: '1、提示条为纯展示，帮助用户了解当前答案匹配进度。',
        permission: '无额外权限限制',
        dataFlow: '匹配统计数据来源于已识别的题目和答案数据',
        exceptions: '全部题目都已匹配答案时，无需显示提示条',
      },
      acceptance: [
        '提示条正确显示匹配统计',
        '待匹配数量正确',
      ],
      source: { decisionFile, decisionObject: '答案匹配状态与统计', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-002',
      title: '题目卡片展示（仅识别题目模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '题目卡片（仅识别题目模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-single',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-single'),
      display: {
        title: '仅识别题目模式下的题目卡片',
        description: '仅识别题目模式下，右侧按题号展示每道题目。每张卡片包含题号、题型、题目内容，以及图片预览区域。不单独展示答案/解析区域。如果用户框选的区域里包含答案或解析内容，由用户通过裁剪功能手动处理。',
        fields: ['题号', '题型', '题目内容', '图片预览'],
        states: ['正常展示', '图片模式：显示题目截图', '编辑模式：显示识别文字'],
      },
      operation: {
        title: '核对与编辑',
        description: '1、用户可切换图片模式查看原始截图，或编辑模式查看AI识别的文字。\n2、在图片模式或编辑模式下，用户都可为每道题修改题型；均可通过点击题号快速定位到右侧对应的题目。\n3、在编辑模式下，可更改AI识别的题目内容。\n4、用户可使用裁剪功能截取题目图片中需要的部分。\n5、用户可为复合题添加子题结构。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于AI识别结果，用户编辑后更新本地状态，加入试卷时传递给下游',
        exceptions: '识别失败时停留在框选识别阶段，不进入本页面',
      },
      acceptance: [
        '题目卡片正确展示',
        '图片/编辑模式可切换',
        '题型和内容可编辑',
        '裁剪功能可用',
      ],
      source: { decisionFile, decisionObject: '仅识别题目模式展示', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-003',
      title: '题目卡片展示（识别题目和答案模式）',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '题目卡片（识别题目和答案模式）',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-card-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-card-stepwise'),
      display: {
        title: '识别题目和答案模式下的题目卡片',
        description: '识别题目和答案模式下，右侧按题号展示每道题目。每张卡片包含题号、题型、题目内容、答案区域和解析区域。未匹配到答案的题目显示对应的辅助提示文案：「未匹配到答案」「未匹配到解析」。填空题按空位展示答案，解答题按子题结构展示子题的答案和解析。',
        fields: ['题号', '题型', '题目内容', '答案', '解析', '匹配状态标签', '子题答案/解析'],
        states: [
          '已匹配答案和解析：正常展示',
          '未匹配到答案：显示「未匹配到答案」标签',
          '未匹配到解析：显示「未匹配到解析」标签',
          '未匹配到答案与解析：显示对应标签',
          '图片模式：显示题目截图',
          '编辑模式：显示识别文字',
        ],
      },
      operation: {
        title: '核对与编辑',
        description: '1、用户可切换图片模式查看原始截图，或编辑模式查看AI识别的文字。\n2、在图片模式或编辑模式下，用户都可为每道题修改题型；均可通过点击题号快速定位到右侧对应的题目；均可编辑AI识别的答案和解析。\n3、在编辑模式下，可更改AI识别的题目内容。\n4、用户可使用裁剪功能截取题目图片中需要的部分。\n5、用户可为复合题添加子题结构。\n6、未匹配答案的题目，用户可在左侧框选答案区域并通过关联弹窗手动关联题号。',
        permission: '无额外权限限制',
        dataFlow: '题目数据来源于AI识别结果和答案匹配结果，用户编辑后更新本地状态，加入试卷时传递给下游',
        exceptions: '识别失败时停留在框选识别阶段',
      },
      acceptance: [
        '题目卡片含答案和解析区域',
        '未匹配提示文案正确显示',
        '填空题按空位显示答案',
        '解答题显示子题结构',
        '图片/编辑模式可切换',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式展示', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-004',
      title: '子题结构与编辑',
      sourceType: 'code+decision',
      objectType: 'region',
      objectName: '子题结构区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-subquestion',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-subquestion'),
      display: {
        title: '子题结构',
        description: '解答题、完形填空、阅读理解等复合题型支持子题结构。在题目卡片中显示子题列表，每个子题包含序号（①②③...）、题型选择器、答案和解析区域。当用户在第二步骤框选题目后，点击开始识别，系统在进行识别的时候，如果存在有子题的大题，需要系统把对应大题的子题结构自动添加，并且子题题型根据每个子题的题干要求自动匹配。父题显示子题匹配进度，例如「2/3 子题已匹配」。用户可点击「+子题」新增空子题。每个子题可独立编辑题型、内容、答案和解析。删除已有内容的子题时弹出确认：「该子题已有答案/解析，删除后内容将一并移除，是否继续？」',
        fields: ['子题序号', '子题题型', '子题答案', '子题解析', '父题匹配进度', '+子题按钮', '删除子题按钮'],
        states: [
          '正常态：子题列表正常展示',
          '新增子题：空子题，待用户填写',
          '删除子题确认弹窗',
        ],
      },
      operation: {
        title: '子题编辑',
        description: '1、题干中的子题标记（如①、②）数量 ≥2 时，自动生成子题结构。\n2、子题题型根据子题题干要求自动匹配，不固定继承父题题型。\n3、答案/解析按子题标记自动拆分到对应子题；无法拆分时保留在父题区并显示「答案解析待人工拆分」。\n4、点击「+子题」新增空子题。\n5、删除子题时如有已有内容，弹窗确认后一并删除。',
        permission: '无额外权限限制',
        dataFlow: '子题数据作为题目数据的一部分，加入试卷时保留完整子题结构',
        exceptions: '题干少于2个子题标记时不自动生成子题结构',
      },
      acceptance: [
        '子题自动拆分正确',
        '子题题型自动匹配',
        '新增子题为空',
        '删除有内容的子题弹窗确认',
        '加入试卷保留子题结构',
      ],
      source: { decisionFile, decisionObject: '子题结构与编辑', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-005',
      title: '答案关联弹窗',
      sourceType: 'code+decision',
      objectType: 'dialog',
      objectName: '答案关联题号弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-link-dialog',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-answer-link-dialog'),
      display: {
        title: '答案关联弹窗',
        description: '用户在左侧框选答案区域后，弹出「请关联题号」弹窗。弹窗标题「请关联题号」，说明文案「为当前框选的答案关联对应的题目」。弹窗内显示已有题目列表，用户可选择题号进行关联。底部有「取消」和「关联」按钮。',
        fields: ['弹窗标题', '说明文案', '题目列表', '关联按钮', '取消按钮'],
        states: [
          '未选择题号：关联按钮置灰',
          '已选择题号：关联按钮绿色高亮',
          '框类型为答案且已关联题号：框上显示关联题号标签',
        ],
      },
      operation: {
        title: '手动关联答案',
        description: '1、用户在左侧资料区框选答案区域后，自动弹出关联弹窗。\n2、用户从题目列表中选择要关联的题号。\n3、答案框只关联父题，识别后再按子题标记自动拆到子题。\n4、点击「关联」后，系统对该答案框进行识别，提取答案和解析内容关联到所选题目。',
        permission: '无额外权限限制',
        dataFlow: '关联关系存储在框数据中，识别完成后答案和解析写入对应的题目',
        exceptions: '关闭弹窗和点击取消按钮时不保存关联，框也取消框选',
      },
      acceptance: [
        '弹窗正确显示题目列表',
        '选择题号后关联按钮可用',
        '关联后答案正确写入题目',
        '答案只关联父题',
      ],
      source: { decisionFile, decisionObject: '答案关联弹窗', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-006',
      title: '图片模式与编辑模式切换',
      sourceType: 'code',
      objectType: 'tab',
      objectName: '图片模式/编辑模式切换按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-view-mode',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-view-mode'),
      display: {
        title: '视图模式切换',
        description: '右侧面板顶部有「图片模式」和「编辑模式」两个切换按钮。图片模式下每道题显示题目截图；编辑模式下显示AI识别的文字内容，可进行编辑。编辑模式下显示提示标签「请注意甄别AI识别内容」。切换时有加载过渡动画。',
        fields: ['图片模式按钮', '编辑模式按钮', '请注意甄别AI识别内容'],
        states: [
          '图片模式选中：绿色背景白色文字',
          '编辑模式选中：绿色背景白色文字',
          '切换中：显示加载动画',
        ],
      },
      operation: {
        title: '切换视图模式',
        description: '1、点击「图片模式」切换到图片视图，查看题目原始截图。\n2、点击「编辑模式」切换到文字视图，可编辑AI识别的题目内容、答案和解析。\n3、切换时显示短暂加载动画。\n4、当用户在图片模式下对图片进行了裁剪操作后，切换到编辑模式，再切回图片模式时，显示的是用户裁剪后的图片数据。同理，用户在编辑模式下编辑了文字数据后切换到图片模式，再切回编辑模式时，回显用户之前编辑过的文字数据。清空用户编辑的图片和文字数据的时机是用户重新上传了资料。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转，仅切换前端展示方式',
        exceptions: '无异常场景',
      },
      acceptance: [
        '两种模式可切换',
        '切换有加载动画',
        '编辑模式可编辑内容',
        '图片模式显示截图',
      ],
      source: { decisionFile, decisionObject: '图片模式/编辑模式', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-007',
      title: '题目图片裁剪功能',
      sourceType: 'code',
      objectType: 'button',
      objectName: '裁剪按钮与裁剪操作',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-crop',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-crop'),
      display: {
        title: '题目图片裁剪',
        description: '每道题目卡片在编辑模式下都有「使用图片」开关，在图片模式下（无论是全局为图片模式，还是编辑模式下部分题型使用了图片）都有裁剪按钮。开启「使用图片」后显示题目图片，用户可点击裁剪按钮进入裁剪模式。裁剪模式下图片四周显示调整手柄，底部显示「取消」和「确认裁剪」按钮。',
        fields: ['使用图片开关', '裁剪按钮', '确认裁剪按钮', '取消按钮', '还原按钮'],
        states: [
          '未开启使用图片：显示AI识别文字',
          '裁剪模式：显示调整手柄和操作按钮',
          '已裁剪：显示裁剪后的图片，可还原到原始图片',
        ],
      },
      operation: {
        title: '裁剪题目图片',
        description: '1、在编辑模式下开启「使用图片」开关后显示题目图片。\n2、在图片模式下，点击裁剪按钮进入裁剪模式，拖动四周手柄调整裁剪范围。\n3、点击「确认裁剪」保存裁剪结果。\n4、点击「取消」退出裁剪模式。\n5、裁剪后可点击「还原」恢复到原始图片。',
        permission: '无额外权限限制',
        dataFlow: '裁剪后的图片数据保存在题目对象中，加入试卷时传递给下游',
        exceptions: '无异常场景',
      },
      acceptance: [
        '编辑模式下有使用图片开关',
        '图片模式下有裁剪按钮',
        '确认裁剪保存结果',
        '取消不保存',
        '可还原到原始图片',
      ],
      source: { decisionFile, decisionObject: '裁剪功能', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-008',
      title: '加入试卷按钮',
      sourceType: 'code+decision',
      objectType: 'button',
      objectName: '加入试卷按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-add-to-paper-btn',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-add-to-paper-btn'),
      display: {
        title: '加入试卷按钮',
        description: '按钮位于弹窗右上角，文案为「加入试卷」。有题目时绿色高亮，无题目时置灰不可点击。',
        fields: ['加入试卷'],
        states: [
          '可用态：有题目 → 绿色背景白色文字可点击',
          '禁用态：无题目 → 灰色背景置灰不可点击',
        ],
      },
      operation: {
        title: '加入试卷',
        description: '1、点击「加入试卷」后，检查是否有题目未匹配答案解析。\n2、如有缺失，弹窗确认：「仍有 X 道题未匹配答案解析，是否继续加入试卷？」（X道题的判断标准：只要该道大题存在答案或解析未匹配，就计1道）。\n3、确认后，将题目数据传递给下游试卷编辑页面，完整保留父题、子题、子题答案/解析、填空空位答案、题型、选项数和题目图片。\n4、加入试卷前保存当前弹窗状态，以便从试卷编辑页返回时恢复。',
        permission: '无额外权限限制',
        dataFlow: '题目数据传递给试卷编辑页面；弹窗状态暂存以供从试卷编辑页返回时恢复',
        exceptions: '如果有未匹配的答案解析，弹窗二次确认后才执行加入操作',
      },
      acceptance: [
        '有题目时按钮可用',
        '无题目时按钮置灰',
        '有缺口时弹窗确认',
        '加入后数据完整传递',
      ],
      source: { decisionFile, decisionObject: '加入试卷', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-009',
      title: '识别失败降级处理',
      sourceType: 'code+decision',
      objectType: 'state',
      objectName: '识别失败降级状态',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-error-fallback',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-error-fallback'),
      display: {
        title: '识别失败处理',
        description: '生产环境下识别失败时，停留在框选识别阶段，不进入核查题目信息页面。显示错误提示「识别失败，请调整框选范围后重试」。',
        fields: ['识别失败提示'],
        states: ['识别失败：停留在框选识别阶段，不进入核查页面'],
      },
      operation: {
        title: '识别失败处理',
        description: '1、AI识别失败时，不生成模拟数据，不进入核查页面。\n2、用户看到错误提示后，可调整框选范围重新识别。\n3、仅识别题目模式下，如果框选区域包含答案/解析，不单独处理，由用户在核查页面通过裁剪功能手动处理。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '识别失败时停留在框选识别阶段，需用户手动重试',
      },
      acceptance: [
        '识别失败停留在框选阶段',
        '显示错误提示',
        '不生成模拟数据',
        '可重试',
      ],
      source: { decisionFile, decisionObject: '识别失败降级', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-010',
      title: '答案/解析自动拆分规则',
      sourceType: 'decision',
      objectType: 'data',
      objectName: '解答题答案/解析拆分规则',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-answer-split-rule',
      anchorStatus: 'planned',
      activate: activateReview('review-step-answer-split-rule'),
      display: {
        title: '答案/解析自动拆分',
        description: '解答题、完形填空等复合题，答案和解析按子题标记自动拆分到对应子题。无法拆分时保留在父题答案/解析区，并显示「答案解析待人工拆分」的提示。拆分后不保留原始文本，只保留拆分后的子题答案/解析。填空题型按空位自动拆分答案。',
        fields: ['子题答案', '子题解析', '答案解析待人工拆分提示', '填空空位答案'],
        states: ['自动拆分成功：答案在各子题中展示', '无法拆分：父题区显示提示文案'],
      },
      operation: {
        title: '拆分规则',
        description: '1、答案/解析只允许按明确子题标记拆分。\n2、无法拆分时保留在父题区，标记「答案解析待人工拆分」。\n3、拆分后不保留原始未拆分文本。\n4、拆分逻辑基于子题数量（≥2个）和子题标记。',
        permission: '无额外权限限制',
        dataFlow: '拆分后的答案/解析写入对应子题对象中',
        exceptions: '无法拆分时保留在父题区',
      },
      acceptance: [
        '按子题标记正确拆分',
        '无法拆分时显示提示',
        '拆分后不保留原始文本',
        '填空按空位拆分',
      ],
      source: { decisionFile, decisionObject: '拆分规则', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-011',
      title: '全局匹配答案按钮（分步模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '全局匹配答案按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-global-match-btn',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-global-match-btn'),
      display: {
        title: '全局匹配答案按钮',
        description: '识别题目和答案模式下，框选识别步骤中，已有题目且尚未匹配答案时，工具栏下方显示「全局匹配答案」按钮。按钮为靛蓝色文字样式。点击后系统从整页资料中自动定位答案区域并关联到已有题目。',
        fields: ['全局匹配答案'],
        states: [
          '显示条件：分步模式 + 已有题目 + 尚未匹配答案',
          '正常态：靛蓝色边框文字',
          '处理中：灰色不可点击',
        ],
      },
      operation: {
        title: '全局匹配答案',
        description: '1、点击「全局匹配答案」后，系统将整页资料发送给AI，从资料中自动定位答案区域并匹配到已有题目。\n2、匹配过程显示进度提示。\n3、匹配完成后统计匹配结果。',
        permission: '无额外权限限制',
        dataFlow: '将整页图片和已有题目信息发送给AI匹配服务',
        exceptions: '匹配过程中按钮不可点击',
      },
      acceptance: [
        '按钮在正确条件下显示',
        '点击后触发匹配',
        '匹配结果正确统计',
      ],
      source: { decisionFile, decisionObject: '全局匹配答案', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-012',
      title: '仅识别题目模式下步骤条可回退',
      sourceType: 'code',
      objectType: 'step',
      objectName: '仅识别题目模式步骤条回退',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-single-mode-back',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-single-mode-back'),
      display: {
        title: '步骤条回退',
        description: '仅识别题目模式下，进入步骤 3（核对识别结果）后，步骤条的第 1 步「选择识别方式」和第 2 步「选择识别内容」为可点击按钮。第 1 步显示 ← 图标，第 2 步显示 ✓ 图标，均为绿色浅背景可点击样式。第 3 步为当前激活态（绿色高亮），第 4 步为灰色未到达态。',
        fields: ['步骤条第1步', '步骤条第2步'],
        states: [
          '第1步：灰色背景 ← 图标，可点击返回模式选择',
          '第2步：绿色浅背景 ✓ 图标，可点击返回框选识别',
          '第3步：绿色高亮当前激活态',
          '第4步：灰色未到达态',
        ],
      },
      operation: {
        title: '回退到前面步骤',
        description: '1、点击步骤条第 1 步，弹出确认弹窗后返回模式选择页面，清空当前识别进度。\n2、点击步骤条第 2 步，回到框选识别页面，保留已框选的区域但取消所有选中状态，用户可重新框选或调整后再次点击「开始识别」。\n3、回退到步骤 2 后，已识别的题目数据保留在右侧。',
        permission: '无额外权限限制',
        dataFlow: '回退时保留已框选区域和已识别题目数据，仅重置选中状态',
        exceptions: '步骤 1 和步骤 2 仅在步骤 3 时可点击回退',
      },
      acceptance: [
        '步骤 1 可点击返回模式选择',
        '步骤 2 可点击返回框选识别',
        '回退后框选保留但不选中',
        '回退后已识别题目保留',
      ],
      source: { decisionFile, decisionObject: '仅识别题目模式步骤条回退', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-013',
      title: '题目卡片上下移动',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片上移/下移按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder'),
      display: {
        title: '题目卡片排序按钮',
        description: '每张题目卡片头部右侧显示上移和下移两个图标按钮。第一张题目的上移按钮置灰不可点击，最后一张题目的下移按钮置灰不可点击；中间题目两个按钮均可点击。鼠标悬停时分别提示「上移题目」和「下移题目」。',
        fields: ['上移题目按钮', '下移题目按钮', '悬停提示'],
        states: [
          '第一张题目：上移按钮置灰',
          '最后一张题目：下移按钮置灰',
          '中间题目：上移和下移按钮均可用',
          '只有一张题目：两个按钮均置灰',
        ],
      },
      operation: {
        title: '调整题目顺序',
        description: '1、点击上移按钮后，当前题目卡片与上一张题目卡片交换位置。\n2、点击下移按钮后，当前题目卡片与下一张题目卡片交换位置。\n3、调整后，核查列表立即按新的顺序展示；题目本身的题号文案不自动改写。\n4、加入试卷时，题目列表按用户调整后的顺序传递给后续试卷编辑页面。',
        permission: '无额外权限限制',
        dataFlow: '排序结果保存在当前核查列表中，影响加入试卷时题目传递顺序',
        exceptions: '位于列表边界的题目不能继续向对应方向移动',
      },
      acceptance: [
        '第一题上移按钮不可用',
        '最后一题下移按钮不可用',
        '点击上移后题目位置向前调整一位',
        '点击下移后题目位置向后调整一位',
        '加入试卷按调整后的顺序传递题目',
      ],
      source: { decisionFile, decisionObject: '题目卡片排序操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-014',
      title: '删除题目卡片',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete'),
      display: {
        title: '题目卡片删除按钮',
        description: '每张题目卡片头部右侧显示删除图标按钮。按钮默认为灰色，悬停时显示红色强调状态，并带有「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['正常态：灰色图标', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除按钮后，该题目卡片从核查列表中移除。\n2、被删除题目的题干、题型、答案、解析、子题和图片核查结果不再进入加入试卷范围。',
        permission: '无额外权限限制',
        dataFlow: '删除后的题目不再传递给后续试卷编辑页面；原有关联答案恢复为未关联状态',
        exceptions: '当前页面不提供删除二次确认和撤销入口，误删后需重新识别或重新补录该题',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '已关联答案恢复为未关联状态',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目卡片删除操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-015',
      title: '题目卡片上下移动（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片上移/下移按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-reorder-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-reorder-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片排序按钮',
        description: '题目+答案模式下，每张题目卡片头部右侧同样显示上移和下移两个图标按钮。第一张题目的上移按钮置灰不可点击，最后一张题目的下移按钮置灰不可点击；中间题目两个按钮均可点击。鼠标悬停时分别提示「上移题目」和「下移题目」。',
        fields: ['上移题目按钮', '下移题目按钮', '悬停提示'],
        states: [
          '第一张题目：上移按钮置灰',
          '最后一张题目：下移按钮置灰',
          '中间题目：上移和下移按钮均可用',
          '只有一张题目：两个按钮均置灰',
        ],
      },
      operation: {
        title: '调整题目顺序',
        description: '1、点击上移按钮后，当前题目卡片与上一张题目卡片交换位置。\n2、点击下移按钮后，当前题目卡片与下一张题目卡片交换位置。\n3、调整后，核查列表立即按新的顺序展示；题目本身的题号文案不自动改写。\n4、加入试卷时，题目、答案和解析按用户调整后的题目顺序传递给后续试卷编辑页面。',
        permission: '无额外权限限制',
        dataFlow: '排序结果保存在当前核查列表中，影响加入试卷时题目、答案和解析的传递顺序',
        exceptions: '位于列表边界的题目不能继续向对应方向移动',
      },
      acceptance: [
        '第一题上移按钮不可用',
        '最后一题下移按钮不可用',
        '点击上移后题目位置向前调整一位',
        '点击下移后题目位置向后调整一位',
        '加入试卷按调整后的顺序传递题目、答案和解析',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片排序操作', relatedFiles },
    },
    {
      id: 'REVIEW_STEP-016',
      title: '删除题目卡片（题目+答案模式）',
      sourceType: 'code',
      objectType: 'button',
      objectName: '题目+答案模式题目卡片删除按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'review-step-question-delete-stepwise',
      anchorStatus: 'implemented',
      activate: activateReview('review-step-question-delete-stepwise'),
      display: {
        title: '题目+答案模式下的题目卡片删除按钮',
        description: '题目+答案模式下，每张题目卡片头部右侧同样显示删除图标按钮。按钮默认为灰色，悬停时显示红色强调状态，并带有「删除题目」提示。',
        fields: ['删除题目按钮', '删除题目提示'],
        states: ['正常态：灰色图标', '悬停态：红色强调'],
      },
      operation: {
        title: '删除题目',
        description: '1、点击删除按钮后，该题目卡片从核查列表中移除。\n2、被删除题目的题干、题型、答案、解析、子题和图片核查结果不再进入加入试卷范围。',
        permission: '无额外权限限制',
        dataFlow: '删除后的题目、答案和解析不再传递给后续试卷编辑页面',
        exceptions: '当前页面不提供删除二次确认和撤销入口，误删后需重新识别或重新补录该题',
      },
      acceptance: [
        '点击删除后题目卡片从列表消失',
        '删除后的题目不加入试卷',
        '删除按钮悬停时有明显红色反馈',
      ],
      source: { decisionFile, decisionObject: '题目+答案模式题目卡片删除操作', relatedFiles },
    },
  ],
  excludedDecisions: [
    {
      objectName: '解答题答案/解析自动分发规则中的不可拆分情况',
      reason: '已纳入 REVIEW_STEP-004 和 REVIEW_STEP-010 的异常处理中',
      sourceDecision: '决策 3',
    },
  ],
};
