import type { ActivationStep, RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
];

const pageName = '资料场景方式选择';
const route = '/homework → 识别作业资料 → 资料场景方式选择步骤';
const moduleName = '识别作业资料';
const decisionFile = '产品文档/prd-workflow/decisions/select-mode-page.decision.md';

function activateSelectModeAnchor(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到资料场景方式选择步骤', step: 'select_mode' },
    { type: 'scrollTo', label: '定位页面对象', anchorId },
    { type: 'highlight', label: '高亮页面对象', anchorId },
  ];
}

function activateFileRoleDialog(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到资料场景方式选择步骤', step: 'select_mode' },
    { type: 'openDialog', label: '打开指定文件用途弹窗', dialog: 'SelectModeFileRoleDialog' },
    { type: 'scrollTo', label: '定位文件用途弹窗', anchorId },
    { type: 'highlight', label: '高亮文件用途弹窗', anchorId },
  ];
}

function activateFrameReviewAnchor(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到选择识别内容步骤', step: 'frame_and_review' },
    { type: 'scrollTo', label: '定位页面对象', anchorId },
    { type: 'highlight', label: '高亮页面对象', anchorId },
  ];
}

export const uploadQuestionDialogSelectModeRegistry: RequirementRegistry = {
  registryId: 'upload-question-dialog-select-mode',
  pageName,
  route,
  module: moduleName,
  description:
    '记录资料场景方式选择页面的完整页面逻辑，覆盖三种识别方式卡片、已上传文件列表、指定文件用途弹窗、返回修改资料或识别方式的确认规则，以及当前三主步骤流程口径。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'SELECT_MODE-001',
      title: '页面标题与引导文案',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '请选择识别方式 / 建议根据您的资料内容，选择合适的处理流程',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-title',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-title'),
      display: {
        title: '页面标题',
        description: '页面居中显示标题「请选择识别方式」，标题下方显示引导文案「建议根据您的资料内容，选择合适的处理流程」。',
        fields: ['请选择识别方式', '建议根据您的资料内容，选择合适的处理流程'],
        states: ['正常显示'],
      },
      operation: {
        title: '无操作',
        description: '标题和引导文案为纯展示文本，用户不可点击或编辑。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['标题文案正确显示为「请选择识别方式」', '引导文案正确显示'],
      source: {
        decisionFile,
        decisionObject: '页面标题与引导文案',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-002',
      title: '仅识别题目模式卡片',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'button',
      objectName: '仅识别题目模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-single-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-single-btn'),
      display: {
        title: '仅识别题目卡片',
        description: '页面第一张模式卡片显示「仅识别题目」。卡片包含蓝色文件图标、一句适用场景说明，以及「资料形态 → 开始识别 → 识别结果」示意图：左侧为放大的单页资料和绿色题目框选框，中间为绿色圆形「开始识别」操作示意，右侧为包含「识别结果」标题和题干1、题干2、题干3示例的结果卡片。',
        fields: ['仅识别题目', '适用场景', '资料示意', '开始识别', '识别结果', '题干1', '题干2', '题干3'],
        states: ['正常态', 'hover 时边框和阴影增强'],
      },
      operation: {
        title: '点击进入仅题目识别流程',
        description: '用户点击「仅识别题目」卡片后，系统直接进入「选择识别内容」步骤。若本次上传了多份文件，所有文件都按题目文件处理。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '用户选择的仅题目识别方式会传递给后续框选和识别流程，后续结果只保留题目内容，不要求答案或解析。',
        exceptions: '进入本页面前由上游保证已有待识别资料；本模式不处理答案和解析内容。',
      },
      acceptance: ['点击卡片后直接进入选择识别内容步骤', '识别模式为仅识别题目', '多文件时不弹出指定文件用途弹窗'],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 选择识别方式后的确认缓冲',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-003',
      title: '题目和答案同文件模式卡片',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'button',
      objectName: '题目+答案（同文件）模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-stepwise-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-stepwise-btn'),
      display: {
        title: '题目和答案同文件卡片',
        description: '页面第二张模式卡片显示「题目+答案」标题和「同文件」标签。卡片包含紫色图标、一句适用场景说明，以及「资料形态 → 开始识别 → 识别结果」示意图：左侧为放大的单页资料，并通过底部圆点手动切换两种同文件资料形态；第一种形态显示一个绿色「题目+答案/解析」整体框选区，第二种形态显示绿色「题目」框选区和紫色「答案/解析」框选区。资料页右边缘展示绿色圆形「开始识别」操作示意；右侧为包含题干、答案和解析骨架的结果卡片。',
        fields: ['题目+答案', '同文件', '适用场景', '资料示意', '题目+答案/解析', '题目', '答案/解析', '切换圆点', '开始识别', '识别结果'],
        states: ['正常态', 'hover 时边框和阴影增强', '点击底部圆点可切换同文件资料示意状态'],
      },
      operation: {
        title: '点击进入同文件题目答案识别流程',
        description: '用户点击「题目+答案（同文件）」卡片后，系统直接进入「选择识别内容」步骤。无论上传一份还是多份文件，都按题目和答案在同一份资料内的方式处理。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '用户选择的同文件题目答案识别方式会传递给后续框选、识别、题目答案核对和答案关联流程。',
        exceptions: '本模式不需要分配文件用途；如果资料为题目和答案分文件存放，用户应选择「题目+答案（不同文件）」模式。',
      },
      acceptance: ['点击卡片后直接进入选择识别内容步骤', '识别模式为题目+答案（同文件）', '多文件时不弹出指定文件用途弹窗'],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 选择识别方式后的确认缓冲',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-008',
      title: '题目和答案不同文件模式卡片',
      sourceType: 'code+decision',
      changeType: 'new',
      changeDate: '6.2',
      objectType: 'button',
      objectName: '题目+答案（不同文件）模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-cross-file-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-cross-file-btn'),
      display: {
        title: '题目和答案不同文件卡片',
        description: '页面第三张模式卡片显示「题目+答案」标题和「不同文件」标签。卡片包含橙色文件图标、一句适用场景说明，以及「资料形态 → 开始识别 → 识别结果」示意图：左侧为统一资料页容器，容器内并列展示两份白色纸张样式文件卡片，分别标记为「题目文件」和「答案文件」；题目文件内显示绿色「题目」框选区，答案文件内显示答案和解析骨架行。资料页右边缘显示「开始识别」操作按钮示意，右侧为包含题干、答案和解析的结果卡片。',
        fields: ['题目+答案', '不同文件', '适用场景', '资料页', '题目文件', '答案文件', '题目框选区', '答案骨架', '开始识别', '识别结果'],
        states: ['正常态', 'hover 时边框和阴影增强', '只有 1 个文件时禁用并降低透明度'],
      },
      operation: {
        title: '点击进入跨文件题目答案识别流程',
        description: '当本次上传至少 2 份文件时，用户点击「题目+答案（不同文件）」卡片后，系统先弹出「指定文件用途」弹窗，让用户为每份文件分配题目文件或答案文件；当只有 1 份文件时，该卡片不可点击。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '用户在该模式下选择的文件用途会传递给后续流程，用于区分题目资料和答案资料；题目文件优先进入自动切题，答案文件用于后续答案关联。',
        exceptions: '只有 1 份文件时禁用该卡片，并通过悬停标题提示「该模式需要有 2 个及以上的文件时才能使用」。',
      },
      acceptance: [
        '至少 2 份文件时卡片可点击并进入指定文件用途弹窗',
        '只有 1 份文件时卡片不可点击',
        '禁用态提示文案正确',
      ],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 模式三+单文件场景 / 选择识别方式后的确认缓冲',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-004',
      title: '已上传文件列表与修改资料入口',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'region',
      objectName: '已上传文件列表区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-list',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-file-list'),
      display: {
        title: '已上传文件列表',
        description: '模式卡片下方显示「已上传的文件：」标题和文件列表。每行展示文件图标、文件名和识别页数，例如「识别12页」；页数来自用户在上传资料时选择的识别范围。列表下方显示「修改资料」入口。',
        fields: ['已上传的文件', '文件名', '识别X页', '修改资料'],
        states: ['有文件时显示', '无页数信息时不显示页数字段'],
      },
      operation: {
        title: '查看文件并返回修改资料',
        description: '用户可以在该区域确认本次已上传文件和识别页数。点击「修改资料」后，返回上传资料步骤，用户可以继续调整本次资料文件和识别范围。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '文件名称和识别页数来自上传资料步骤；返回修改后，新的文件和识别范围继续作为本页面选择识别方式的输入。',
        exceptions: '进入本页面前由上游保证已有待识别资料，因此本页面不额外处理无资料空状态。',
      },
      acceptance: ['文件列表正确显示文件名', '有识别范围时显示识别页数', '点击修改资料可返回上传资料步骤'],
      source: {
        decisionFile,
        decisionObject: '已上传文件列表中缺少页数信息 / 步骤2文件列表与步骤1一致性 / 无已上传文件时的选择模式空状态',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-005',
      title: '指定文件用途弹窗',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'dialog',
      objectName: '指定文件用途弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-role-dialog',
      anchorStatus: 'implemented',
      activate: activateFileRoleDialog('select-mode-file-role-dialog'),
      display: {
        title: '指定文件用途弹窗',
        description: '用户选择「题目+答案（不同文件）」且需要分配文件用途时，页面显示「指定文件用途」弹窗。弹窗展示文件用途说明、文件列表、每份文件的「题目文件」「答案文件」按钮，以及底部「取消」「确认，开始处理」按钮。',
        fields: ['指定文件用途', '题目文件', '答案文件', '取消', '确认，开始处理'],
        states: [
          '题目文件按钮选中态：绿色背景白色文字',
          '答案文件按钮选中态：绿色背景白色文字',
          '未选中态：白底灰字',
          '有文件未分配角色时确认按钮禁用',
          '所有文件均已分配角色时确认按钮可点击',
        ],
      },
      operation: {
        title: '分配题目文件和答案文件',
        description: '每份文件独立选择用途，点击「题目文件」或「答案文件」后只影响当前文件；再次点击已选中的按钮可取消选择并恢复为未分配。只要每份文件都有明确角色，就可以点击「确认，开始处理」进入后续流程；全题目或全答案也允许确认，后续空结果或缺少答案由后续步骤承接。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '文件用途分配结果会传递给后续流程，用于排序展示题目文件和答案文件、决定自动切题范围和答案关联范围。',
        exceptions: '存在未分配角色的文件时，「确认，开始处理」按钮置灰不可点击；点击「取消」或右上角关闭按钮后，关闭弹窗并取消已选识别方式，用户可重新选择模式。',
      },
      acceptance: [
        '每份文件可以独立选择题目文件或答案文件',
        '已选按钮再次点击可取消选择',
        '所有文件都有角色时确认按钮可用',
        '全题目或全答案也可确认进入后续流程',
        '取消或关闭弹窗后可重新选择识别方式',
      ],
      source: {
        decisionFile,
        decisionObject: '文件角色分配弹窗 / 跨文件模式的文件角色合法性',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-006',
      title: '返回上传资料或修改识别方式确认',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'button',
      objectName: '修改资料 / 修改识别方式入口',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-return-actions',
      anchorStatus: 'implemented',
      activate: activateFrameReviewAnchor('select-mode-return-actions'),
      display: {
        title: '后续步骤返回修改入口',
        description: '进入后续识别步骤后，页面提供「修改资料」和「修改识别方式」入口；「修改资料」放在资料预览区右侧的「更多工具」悬浮菜单中，「修改识别方式」保留在顶部步骤条右侧的识别方式标签悬浮操作中。当返回操作会影响当前识别进度时，页面弹出确认弹窗，提示用户返回会清空当前进度。',
        fields: ['更多工具', '修改资料', '识别方式标签', '修改识别方式', '确认修改资料吗？', '确认修改识别方式吗？'],
        states: ['无识别进度时可直接返回', '已有识别进度或草稿时需要确认'],
      },
      operation: {
        title: '确认后清空识别进度并返回',
        description: '所有从后续步骤返回「上传资料」或「选择识别方式」的入口，只要已有文件用途、框选、已识别题目或答案关联草稿，都需要先弹窗确认。用户确认后，系统清空文件用途、框选、已识别题目和答案关联，再返回对应步骤；用户取消后保持当前步骤和已有进度不变。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '确认返回后，本次识别流程中的文件用途、框选、题目识别结果和答案关联草稿会被清空，用户需要重新选择识别方式或重新调整资料。',
        exceptions: '如果当前没有会被清空的识别进度或草稿，可以直接返回目标步骤，不额外弹出确认。',
      },
      acceptance: [
        '已有角色分配、框选、题目或答案关联草稿时返回会先弹窗确认',
        '确认后清空本次识别进度并返回目标步骤',
        '取消后保留当前页面和已有识别进度',
      ],
      source: {
        decisionFile,
        decisionObject: '从后续步骤返回选择识别方式或上传资料',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-007',
      title: '选择识别方式页步骤条',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'step',
      objectName: '选择识别方式页步骤条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-step-bar',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-step-bar'),
      display: {
        title: '三主步骤流程展示',
        description: '页面顶部采用四主步骤口径展示流程：1 上传资料、2 选择识别方式、3 选择识别内容、4 核对识别结果。当前处于选择识别方式页时，第 2 步高亮，其余步骤按已完成或未到达状态展示；手动关联答案作为第 4 步内的子状态，不再作为单独步骤展示。步骤条右侧承载临时操作区，展示操作说明、加入试卷等入口；进入后续识别步骤后，右侧同时显示当前识别方式标签，悬浮后可修改识别方式。',
        fields: ['上传资料', '选择识别方式', '选择识别内容', '核对识别结果', '识别方式标签', '操作说明', '加入试卷'],
        states: [
          '当前步骤：绿色高亮并显示脉冲圆点',
          '已完成步骤：浅绿色背景和完成图标',
          '未到达步骤：灰色态',
          '手动关联答案作为核对识别结果步骤内的子状态，不额外显示步骤节点',
          '后续识别步骤显示当前识别方式标签',
        ],
      },
      operation: {
        title: '查看当前流程位置',
        description: '步骤条帮助用户理解当前识别流程位置。用户在后续步骤可点击已完成步骤返回调整；返回会按页面返回确认规则处理，避免误清空识别进度。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '步骤条不单独产生业务数据，只反映本次识别流程当前所处阶段。',
        exceptions: '未到达步骤不可点击；返回已完成步骤时是否需要确认，由当前是否已有识别进度或草稿决定。',
      },
      acceptance: [
        '步骤条按三主步骤口径展示',
        '选择识别方式页第 2 步为当前态',
        '后续步骤返回已完成步骤时遵循返回确认规则',
      ],
      source: {
        decisionFile,
        decisionObject: '选择识别方式页的步骤条结构',
        relatedFiles,
      },
    },
  ],
  excludedDecisions: [
    {
      objectName: '示例图片 alt 文案',
      reason: '示例图片 alt 文案只作为图片兜底信息，不作为页面业务逻辑卡片展示。',
      sourceDecision: '决策 1B',
    },
    {
      objectName: '多文件提示文案',
      reason: '多文件提示不在本页面展示，不作为页面业务逻辑卡片展示。',
      sourceDecision: '决策 8 自定义方案',
    },
    {
      objectName: '无已上传文件时的选择模式空状态',
      reason: '进入本页面时已有待识别资料，因此不单独生成无资料空状态需求卡片。',
      sourceDecision: '决策 20 自定义方案',
    },
  ],
};
