import type { ActivationStep, RequirementRegistry } from './schema';

const relatedFiles = [
  'src/components/UploadQuestionDialog.tsx',
  'src/app/homework/page.tsx',
];

const pageName = '选择识别方式';
const route = '/homework → 识别作业资料 → 选择识别方式';
const moduleName = '识别作业资料';
const decisionFile = '产品文档/prd-workflow/decisions/select-mode-page.decision.md';

function activateSelectModeAnchor(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到选择识别方式', step: 'select_mode' },
    { type: 'scrollTo', label: '定位页面对象', anchorId },
    { type: 'highlight', label: '高亮页面对象', anchorId },
  ];
}

function activateFileRoleDialog(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到选择识别方式', step: 'select_mode' },
    { type: 'openDialog', label: '打开指定文件用途弹窗', dialog: 'SelectModeFileRoleDialog' },
    { type: 'scrollTo', label: '定位文件用途弹窗', anchorId },
    { type: 'highlight', label: '高亮文件用途弹窗', anchorId },
  ];
}

function activateFrameReviewAnchor(anchorId: string): ActivationStep[] {
  return [
    { type: 'openDialog', label: '打开识别作业资料弹窗', dialog: 'UploadQuestionDialog' },
    { type: 'setStep', label: '切换到选择识别内容', step: 'frame_and_review' },
    { type: 'scrollTo', label: '定位页面对象', anchorId },
    { type: 'highlight', label: '高亮页面对象', anchorId },
  ];
}

export const uploadQuestionDialogSelectModeRegistry: RequirementRegistry = {
  registryId: 'upload-question-dialog-select-mode',
  pageName,
  route,
  module: moduleName,
  description:
    '记录步骤 2「选择识别方式」的完整页面逻辑，覆盖三种识别方式卡片、已上传文件列表、指定文件用途弹窗、返回修改资料或识别方式的确认规则，以及当前前端展示的流程口径。',
  sourceDecisionFile: decisionFile,
  relatedFiles,
  requirements: [
    {
      id: 'SELECT_MODE-001',
      title: '页面标题与引导文案',
      sourceType: 'code+decision',
      objectType: 'copy',
      objectName: '请选择识别方式 / 建议根据您的资料内容，选择合适的处理流程',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-title',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-title'),
      display: {
        title: '页面标题',
        description: '页面居中显示标题「请选择识别方式」，下方显示引导文案「建议根据您的资料内容，选择合适的处理流程」。',
        fields: ['请选择识别方式', '建议根据您的资料内容，选择合适的处理流程'],
      },
      operation: {
        title: '无操作',
        description: '纯展示文本，不可点击、不可编辑。',
        permission: '无额外权限限制',
        dataFlow: '无额外数据流转',
        exceptions: '无异常场景',
      },
      acceptance: ['标题文案正确显示为「请选择识别方式」', '引导文案正确显示'],
      source: {
        decisionFile,
        decisionObject: '页面标题与引导文案',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-002',
      title: '仅识别题目模式卡片',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'button',
      objectName: '仅识别题目模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-single-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-single-btn'),
      display: {
        title: '仅识别题目卡片',
        description: '第一张卡片显示「仅识别题目」标题、蓝色图标和适用场景说明。卡片内展示流程示意图：左侧为单页资料和绿色题目框选区，中间为「开始识别」流程示意，右侧为「识别结果」卡片（含题干1/2/3示例）。',
        fields: ['仅识别题目', '适用场景', '资料示意', '开始识别', '识别结果', '题干1', '题干2', '题干3'],
        states: ['hover 时边框和阴影增强', '「开始识别」仅作为流程示意展示'],
      },
      operation: {
        title: '点击进入仅题目识别',
        description: '点击卡片后直接进入「选择识别内容」步骤。多文件时所有文件均按题目文件处理。卡片内「开始识别」为流程示意，不单独响应点击。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '仅题目识别方式传递给后续流程，后续结果只保留题目内容。',
        exceptions: '本模式不处理答案和解析内容。',
      },
      acceptance: ['点击卡片后直接进入选择识别内容', '识别模式为仅识别题目', '多文件时不弹出指定文件用途弹窗', '卡片内「开始识别」不作为独立按钮处理'],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 选择识别方式后的确认缓冲 / 识别方式卡片内「开始识别」示意',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-003',
      title: '题目和答案同文件模式卡片',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'button',
      objectName: '题目+答案（同文件）模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-stepwise-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-stepwise-btn'),
      display: {
        title: '题目和答案同文件卡片',
        description: '第二张卡片显示「题目+答案」标题和「同文件」标签、紫色图标和适用场景说明。卡片内展示流程示意图：左侧为单页资料且两种状态自动轮播——状态一显示绿色「题目+答案/解析」整体框选区，状态二显示绿色「题目」框选区和紫色「答案/解析」框选区；中间为「开始识别」流程示意；右侧为含题干、答案和解析骨架的结果卡片。',
        fields: ['题目+答案', '同文件', '适用场景', '题目+答案/解析', '题目', '答案/解析', '开始识别', '识别结果'],
        states: ['hover 时边框和阴影增强', '左侧资料页两种状态自动轮播', '「开始识别」仅作为流程示意展示'],
      },
      operation: {
        title: '点击进入同文件识别',
        description: '点击卡片后直接进入「选择识别内容」步骤。无论几份文件均按题目和答案在同一资料内处理。卡片内「开始识别」为流程示意，不单独响应点击。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '同文件识别方式传递给后续框选、识别、核对和答案关联流程。',
        exceptions: '本模式不分配文件用途。如资料为题目和答案分文件存放，应选择「题目+答案（不同文件）」模式。',
      },
      acceptance: ['点击卡片后直接进入选择识别内容', '识别模式为题目+答案（同文件）', '多文件时不弹出指定文件用途弹窗', '卡片内「开始识别」不作为独立按钮处理'],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 选择识别方式后的确认缓冲 / 识别方式卡片内「开始识别」示意',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-008',
      title: '题目和答案不同文件模式卡片',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'button',
      objectName: '题目+答案（不同文件）模式选择按钮',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-cross-file-btn',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-cross-file-btn'),
      display: {
        title: '题目和答案不同文件卡片',
        description: '第三张卡片显示「题目+答案」标题和「不同文件」标签、橙色图标和适用场景说明。卡片内展示流程示意图：左侧并列展示「题目文件」和「答案文件」卡片，题目文件内显示绿色框选区，答案文件内显示答案和解析骨架行；中间为「开始识别」流程示意；右侧为含题干、答案和解析的结果卡片。只有 1 个文件时，卡片可见但降低透明度，常驻显示「该模式需要 2 个及以上文件」。',
        fields: ['题目+答案', '不同文件', '题目文件', '答案文件', '开始识别', '识别结果'],
        states: ['hover 时边框和阴影增强', '只有 1 个文件时禁用并降低透明度', '只有 1 个文件时常驻显示禁用原因', '「开始识别」仅作为流程示意展示'],
      },
      operation: {
        title: '点击进入跨文件识别',
        description: '至少 2 份文件时，点击卡片后先弹出「指定文件用途」弹窗，为每份文件分配题目文件或答案文件。只有 1 份文件时卡片不可点击。卡片内「开始识别」为流程示意，不单独响应点击。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '文件用途分配结果传给后续流程，用于区分题目和答案资料；题目文件优先自动切题，答案文件用于后续答案关联。',
        exceptions: '只有 1 份文件时卡片禁用，常驻显示「该模式需要 2 个及以上文件」。',
      },
      acceptance: [
        '至少 2 份文件时卡片可点击并进入指定文件用途弹窗',
        '只有 1 份文件时卡片不可点击',
        '只有 1 份文件时卡片内常驻显示禁用原因',
        '卡片内「开始识别」不作为独立按钮处理',
      ],
      source: {
        decisionFile,
        decisionObject: '识别方式卡片结构 / 模式三+单文件场景 / 选择识别方式后的确认缓冲 / 跨文件模式单文件禁用提示 / 识别方式卡片内「开始识别」示意',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-004',
      title: '已上传文件列表与修改资料入口',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.2',
      objectType: 'region',
      objectName: '已上传文件列表区域',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-list',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-file-list'),
      display: {
        title: '已上传文件列表',
        description: '模式卡片下方显示「已上传的文件：」标题和文件列表。每行展示文件图标、文件名和识别页数（如「识别12页」）。',
        fields: ['已上传的文件', '文件名', '识别X页'],
        states: ['有文件时显示', '无页数信息时不显示页数字段'],
      },
      operation: {
        title: '查看文件',
        description: '用户可在此区域确认已上传文件和识别页数。返回步骤1 通过顶部步骤条点击「上传资料」完成。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '文件名称和识别页数来自上传资料步骤。',
        exceptions: '进入本页面前已保证有资料，不处理无资料空状态。',
      },
      acceptance: ['文件列表正确显示文件名', '有识别范围时显示识别页数'],
      source: {
        decisionFile,
        decisionObject: '已上传文件列表中缺少页数信息 / 步骤2文件列表与步骤1一致性 / 无已上传文件时的选择模式空状态',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-005',
      title: '指定文件用途弹窗',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'dialog',
      objectName: '指定文件用途弹窗',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-file-role-dialog',
      anchorStatus: 'implemented',
      activate: activateFileRoleDialog('select-mode-file-role-dialog'),
      display: {
        title: '指定文件用途弹窗',
        description: '选择「题目+答案（不同文件）」且需分配文件用途时弹出此弹窗。展示文件用途说明、文件列表、每份文件的「题目文件」「答案文件」按钮，以及底部「取消」「确认，开始处理」按钮。再次进入时恢复上次临时分配。',
        fields: ['指定文件用途', '题目文件', '答案文件', '取消', '确认，开始处理'],
        states: [
          '题目文件/答案文件按钮选中态：绿色背景白色文字',
          '未选中态：白底灰字',
          '有文件未分配角色时确认按钮禁用',
          '所有文件均已分配时确认按钮可点击',
        ],
      },
      operation: {
        title: '分配文件用途',
        description: '每份文件独立选择用途，点击「题目文件」或「答案文件」只影响当前文件；再次点击已选中按钮可取消选择。所有文件均有角色后可点击「确认，开始处理」进入后续流程；全题目或全答案也允许确认，后续由对应步骤承接。取消或关闭弹窗时，取消当前已选识别方式但保留本次临时分配，再次进入时恢复。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '文件用途分配结果传给后续流程，用于排序展示题目和答案文件、决定自动切题范围和答案关联范围。',
        exceptions: '存在未分配角色的文件时，「确认，开始处理」按钮置灰不可点击。',
      },
      acceptance: [
        '每份文件可以独立选择题目文件或答案文件',
        '已选按钮再次点击可取消选择',
        '所有文件都有角色时确认按钮可用',
        '全题目或全答案也可确认进入后续流程',
        '取消或关闭弹窗后可重新选择识别方式',
        '取消或关闭后再次进入弹窗应恢复上次临时分配',
      ],
      source: {
        decisionFile,
        decisionObject: '文件角色分配弹窗 / 跨文件模式的文件角色合法性 / 指定文件用途弹窗取消后的临时分配',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-006',
      title: '修改识别方式确认',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'button',
      objectName: '修改识别方式入口',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-return-actions',
      anchorStatus: 'implemented',
      activate: activateFrameReviewAnchor('select-mode-return-actions'),
      display: {
        title: '修改识别方式入口',
        description: '进入后续步骤后，顶部步骤条右侧显示当前识别方式标签。悬浮标签时显示「修改识别方式」入口。已有识别结果时点击弹出确认弹窗：标题「确认修改识别方式吗？」，说明「修改识别方式，将清空已有的识别内容」。',
        fields: ['识别方式标签', '修改识别方式', '确认修改识别方式吗？', '修改识别方式，将清空已有的识别内容'],
        states: ['无识别进度时直接返回选择识别方式', '已有识别进度时需确认'],
      },
      operation: {
        title: '确认后清空进度并返回',
        description: '1、所有从后续步骤返回「选择识别方式」的入口，只要有文件用途、框选、已识别题目或答案，均需弹窗确认。\n2、确认后系统清空文件用途、框选、已识别题目和答案，再返回选择识别方式。\n3、取消后保持当前步骤和已有进度不变。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '确认返回后，本次流程中的文件用途、框选、识别结果和答案被清空，用户需重新选择识别方式。',
        exceptions: '当前无识别进度或草稿时，直接返回目标步骤，不弹出确认。',
      },
      acceptance: [
        '已有角色分配、框选、题目或答案时修改识别方式会先弹窗确认',
        '修改识别方式应显示对应确认文案',
        '确认后清空本次识别进度并返回选择识别方式步骤',
        '取消后保留当前页面和已有识别进度',
      ],
      source: {
        decisionFile,
        decisionObject: '从后续步骤返回选择识别方式 / 返回修改确认弹窗文案',
        relatedFiles,
      },
    },
    {
      id: 'SELECT_MODE-007',
      title: '选择识别方式页步骤条',
      sourceType: 'code+decision',
      changeType: 'changed',
      changeDate: '6.4',
      objectType: 'step',
      objectName: '选择识别方式页步骤条',
      module: moduleName,
      pageName,
      route,
      anchorId: 'select-mode-step-bar',
      anchorStatus: 'implemented',
      activate: activateSelectModeAnchor('select-mode-step-bar'),
      display: {
        title: '步骤条展示',
        description: '页面顶部按当前前端效果展示 4 个主步骤：1 上传资料、2 选择识别方式、3 选择识别内容、4 核对识别结果。当前页面第 2 步高亮，其余步骤按已完成或未到达状态展示。步骤条右侧展示操作说明入口和「加入试卷」按钮，步骤 2 中「加入试卷」为禁用态。进入后续步骤后，右侧同时显示当前识别方式标签。操作说明弹窗展示完整流程说明（含上传资料至加入试卷 5 个节点），其中「加入试卷」不作为顶部步骤条的第 5 个步骤。',
        fields: ['上传资料', '选择识别方式', '选择识别内容', '核对识别结果', '识别方式标签', '操作说明', '加入试卷'],
        states: [
          '当前步骤：绿色高亮并显示脉冲圆点',
          '已完成步骤：浅绿色背景和完成图标',
          '未到达步骤：灰色态',
          '步骤 2 的加入试卷为禁用态',
        ],
      },
      operation: {
        title: '流程导航',
        description: '步骤条展示当前识别流程所处阶段。顶部「上传资料」步骤可点击返回步骤 1：无识别进度时直接返回，已有进度时弹窗确认「确认返回上传资料步骤吗？返回上传资料步骤，将清空当前已识别的信息」。后续步骤可点击已完成步骤返回调整，按页面返回确认规则处理。步骤 2「加入试卷」为禁用态，hover 或点击时提示「完成题目识别并生成题目后，才能加入试卷」。',
        permission: '沿用识别作业资料弹窗的使用权限',
        dataFlow: '步骤条不产生业务数据，只反映当前流程阶段。',
        exceptions: '未到达步骤不可点击。未生成题目数据前不允许加入试卷。',
      },
      acceptance: [
        '步骤条按当前前端 4 个主步骤展示',
        '选择识别方式页第 2 步为当前态',
        '操作说明弹窗按当前页面展示完整流程说明，且不改变顶部 4 个主步骤口径',
        '顶部上传资料步骤的返回确认文案符合已确认口径',
        '步骤 2 的加入试卷按钮禁用且给出不可用原因',
        '后续步骤返回已完成步骤时遵循返回确认规则',
      ],
      source: {
        decisionFile,
        decisionObject: '选择识别方式页的步骤条结构 / 顶部「上传资料」步骤返回入口 / 顶部操作区「加入试卷」按钮 / 操作说明流程总览口径',
        relatedFiles,
      },
    },
  ],
  excludedDecisions: [
    {
      objectName: '示例图片 alt 文案',
      reason: '示例图片 alt 文案只作为图片兜底信息，不作为页面业务逻辑卡片展示。',
      sourceDecision: '决策 1B',
    },
    {
      objectName: '多文件提示文案',
      reason: '多文件提示不在本页面展示，不作为页面业务逻辑卡片展示。',
      sourceDecision: '决策 8 自定义方案',
    },
    {
      objectName: '无已上传文件时的选择模式空状态',
      reason: '进入本页面时已有待识别资料，因此不单独生成无资料空状态需求卡片。',
      sourceDecision: '决策 20 自定义方案',
    },
  ],
};
